package google

import "testing"

// TestStripDefaultAPIArtifact_PreservesLeadingSpaceOnPlainText pins
// the streaming-delta contract: a chunk that doesn't contain the
// default_api narration artifact must pass through verbatim. The
// previous implementation ran an unconditional TrimLeft after the
// regex strip, which silently ate the leading space of every Gemini
// text delta — successive chunks like " world", " is", " great"
// concatenated client-side as "worldisgreat".
func TestStripDefaultAPIArtifact_PreservesLeadingSpaceOnPlainText(t *testing.T) {
	cases := []struct {
		name, in string
	}{
		{"leading space", " world"},
		{"multiple leading spaces", "   indented"},
		{"leading newline", "\nnext line"},
		{"leading tab", "\tindented"},
		{"leading comma in actual prose", ", a continuation"},
		{"plain ascii word", "hello"},
		{"sentence with mid spaces", "hello world how are you"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := stripDefaultAPIArtifact(tc.in)
			if got != tc.in {
				t.Errorf("plain text chunk should pass through unchanged\n in:  %q\n got: %q", tc.in, got)
			}
		})
	}
}

// TestStripDefaultAPIArtifact_StripsAndCleansAfterMatch confirms the
// original purpose is preserved: when the default_api artifact is
// present, strip it AND clean leading whitespace/punctuation the
// strip leaves behind.
func TestStripDefaultAPIArtifact_StripsAndCleansAfterMatch(t *testing.T) {
	cases := []struct {
		name, in, want string
	}{
		{"bracketed artifact in mid-prose", "Sure, [image, generated by default_api:generate_image]Here's the image.", "Sure, Here's the image."},
		{"chunk-boundary split swallows leading bracket", "image, generated by default_api:generate_image, then the prose", "then the prose"},
		{"strip leaves leading newline + cleans", "generated by default_api:foo_bar\nNext paragraph.", "Next paragraph."},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := stripDefaultAPIArtifact(tc.in)
			if got != tc.want {
				t.Errorf("in:   %q\ngot:  %q\nwant: %q", tc.in, got, tc.want)
			}
		})
	}
}

// TestStripDefaultAPIArtifact_ConcatPreservesWordBoundaries simulates
// the streaming-aggregation case the original bug actually surfaced:
// the server's per-chunk strip used to eat the leading space, so the
// concatenated stream lost word boundaries. Pin the round-trip.
func TestStripDefaultAPIArtifact_ConcatPreservesWordBoundaries(t *testing.T) {
	chunks := []string{"Hello", " world", " how", " are", " you"}
	var concat string
	for _, c := range chunks {
		concat += stripDefaultAPIArtifact(c)
	}
	const want = "Hello world how are you"
	if concat != want {
		t.Errorf("got %q want %q", concat, want)
	}
}
