// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector "github.com/pgvector/pgvector-go"
)

const clearMessageEmbedding = `-- name: ClearMessageEmbedding :exec
UPDATE messages
SET embedding       = NULL,
    embedding_model = NULL,
    embedding_at    = NULL
WHERE id = $1
`

// Reset the triple when a model swap orphans the existing vector.
// Backfill picks the row up via ListUnembeddedMessages on the next
// pass. CHECK invariant still holds (all three back to NULL).
func (q *Queries) ClearMessageEmbedding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMessageEmbedding, id)
	return err
}

const countAssistantMessagesCapped = `-- name: CountAssistantMessagesCapped :one
SELECT COUNT(*) FROM (
    SELECT 1 FROM messages
    WHERE context_id = $1 AND role = 'assistant'
    LIMIT 2
) capped
`

// Capped at 2: the auto-title hook only distinguishes "exactly one
// assistant turn exists" from everything else, and it fires on EVERY
// assistant materialization — a full-context list per turn just to
// count was the cost.
func (q *Queries) CountAssistantMessagesCapped(ctx context.Context, contextID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAssistantMessagesCapped, contextID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnembeddedMessages = `-- name: CountUnembeddedMessages :one
SELECT COUNT(*)::INT FROM messages m
JOIN contexts ctx ON ctx.id = m.context_id
JOIN conversations c ON c.id = ctx.conversation_id
WHERE m.embedding IS NULL
  AND m.role IN ('user', 'assistant', 'context')
  AND m.content <> ''
  AND c.user_id = $1
`

// Drives the "X / Y embedded" progress chip in the settings UI.
// Cheap even on millions of rows because the partial
// messages_unembedded_created_at index is exactly this predicate.
// Scoped to a user so the chip means "MY unembedded messages."
func (q *Queries) CountUnembeddedMessages(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnembeddedMessages, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAssistantMessageWithUsage = `-- name: CreateAssistantMessageWithUsage :one
INSERT INTO messages (
    id, context_id, parent_id, role, content,
    raw_content, thinking, thinking_provider_type, thinking_rendered_text,
    thinking_duration_ms,
    provider_id, model_id,
    input_tokens, output_tokens, cache_read_tokens, cache_write_tokens,
    reasoning_tokens, provider_usage_raw,
    input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd,
    tool_cost_usd, total_cost_usd,
    error_payload,
    explicit_cache_attached,
    tool_calls,
    finish_reason
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10,
    $11, $12,
    $13, $14, $15, $16,
    $17, $18,
    $19, $20, $21, $22,
    $23, $24,
    $25,
    $26,
    $27,
    $28
)
RETURNING id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers
`

type CreateAssistantMessageWithUsageParams struct {
	ID                    uuid.UUID
	ContextID             uuid.UUID
	ParentID              *uuid.UUID
	Role                  string
	Content               string
	RawContent            *string
	Thinking              []byte
	ThinkingProviderType  *string
	ThinkingRenderedText  *string
	ThinkingDurationMs    *int32
	ProviderID            *uuid.UUID
	ModelID               *string
	InputTokens           *int32
	OutputTokens          *int32
	CacheReadTokens       *int32
	CacheWriteTokens      *int32
	ReasoningTokens       *int32
	ProviderUsageRaw      []byte
	InputCostUsd          pgtype.Numeric
	OutputCostUsd         pgtype.Numeric
	CacheReadCostUsd      pgtype.Numeric
	CacheWriteCostUsd     pgtype.Numeric
	ToolCostUsd           pgtype.Numeric
	TotalCostUsd          pgtype.Numeric
	ErrorPayload          []byte
	ExplicitCacheAttached *bool
	ToolCalls             []byte
	FinishReason          *string
}

// Used by the stream supervisor at materialization. Allows the assistant turn
// (or the compression_summary record) to be inserted with usage + cost
// columns populated atomically. error_payload is set when the stream
// terminated in an errored/cancelled state — captures the failure inline so
// the UI can render the message as a first-class errored history entry.
// thinking_duration_ms records the elapsed time (ms) between the first and
// last thinking_delta chunk seen on the run; NULL when the assistant didn't
// reason at all.
func (q *Queries) CreateAssistantMessageWithUsage(ctx context.Context, arg CreateAssistantMessageWithUsageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createAssistantMessageWithUsage,
		arg.ID,
		arg.ContextID,
		arg.ParentID,
		arg.Role,
		arg.Content,
		arg.RawContent,
		arg.Thinking,
		arg.ThinkingProviderType,
		arg.ThinkingRenderedText,
		arg.ThinkingDurationMs,
		arg.ProviderID,
		arg.ModelID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.ReasoningTokens,
		arg.ProviderUsageRaw,
		arg.InputCostUsd,
		arg.OutputCostUsd,
		arg.CacheReadCostUsd,
		arg.CacheWriteCostUsd,
		arg.ToolCostUsd,
		arg.TotalCostUsd,
		arg.ErrorPayload,
		arg.ExplicitCacheAttached,
		arg.ToolCalls,
		arg.FinishReason,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, context_id, parent_id, role, content,
    raw_content, thinking, thinking_provider_type, thinking_rendered_text,
    provider_id, model_id, message_headers, message_trailers
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13
)
RETURNING id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers
`

type CreateMessageParams struct {
	ID                   uuid.UUID
	ContextID            uuid.UUID
	ParentID             *uuid.UUID
	Role                 string
	Content              string
	RawContent           *string
	Thinking             []byte
	ThinkingProviderType *string
	ThinkingRenderedText *string
	ProviderID           *uuid.UUID
	ModelID              *string
	MessageHeaders       *string
	MessageTrailers      *string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ContextID,
		arg.ParentID,
		arg.Role,
		arg.Content,
		arg.RawContent,
		arg.Thinking,
		arg.ThinkingProviderType,
		arg.ThinkingRenderedText,
		arg.ProviderID,
		arg.ModelID,
		arg.MessageHeaders,
		arg.MessageTrailers,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}

const createWelcomeMessage = `-- name: CreateWelcomeMessage :one
INSERT INTO messages (
    id, context_id, parent_id, role, content, is_welcome
) VALUES (
    $1, $2, $3, 'assistant', $4, TRUE
)
RETURNING id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers
`

type CreateWelcomeMessageParams struct {
	ID        uuid.UUID
	ContextID uuid.UUID
	ParentID  *uuid.UUID
	Content   string
}

// Insert the profile's snapshot welcome message at conversation-create
// time. Role is hard-coded to 'assistant' (the welcome is a greeting,
// not a system instruction) and is_welcome is set so clients can
// gate a fake-stream reveal animation on first open.
func (q *Queries) CreateWelcomeMessage(ctx context.Context, arg CreateWelcomeMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createWelcomeMessage,
		arg.ID,
		arg.ContextID,
		arg.ParentID,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}

const deleteMessageByID = `-- name: DeleteMessageByID :exec
DELETE FROM messages WHERE id = $1
`

// The cascade=true path. With ON DELETE CASCADE on parent_id (migration 00006),
// this single DELETE removes the descendant subtree too.
func (q *Queries) DeleteMessageByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageByID, id)
	return err
}

const getCompressionSummaryInContext = `-- name: GetCompressionSummaryInContext :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers FROM messages
WHERE context_id = $1 AND role = 'compression_summary'
ORDER BY created_at DESC
LIMIT 1
`

// Returns the (single) compression_summary message in a context, if any. Used
// by PromoteCompactionToNewContext to read the (possibly user-edited) content
// and seed the new context's role=context message.
func (q *Queries) GetCompressionSummaryInContext(ctx context.Context, contextID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getCompressionSummaryInContext, contextID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}

const getContextLeafMessage = `-- name: GetContextLeafMessage :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers FROM messages m
WHERE m.context_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM messages c
    WHERE c.parent_id = m.id
  )
ORDER BY m.id DESC
LIMIT 1
`

// Returns the leaf of a context's message tree: the message that no other
// message in the same context references as a parent. When the context has
// multiple dangling branches (shouldn't happen in normal use), returns the
// one with the greatest id (most recently created per UUIDv7 monotonicity).
// Returns no rows when the context is truly empty.
// NOT EXISTS rather than NOT IN: the planner runs this as an anti-join
// probing the messages_parent index per candidate row, where NOT IN
// materialized the full distinct-parent set on every call (and carries
// NULL-semantics traps besides).
func (q *Queries) GetContextLeafMessage(ctx context.Context, contextID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getContextLeafMessage, contextID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}

const getContextRoleMessageInContext = `-- name: GetContextRoleMessageInContext :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers FROM messages
WHERE context_id = $1 AND role = 'context'
ORDER BY created_at
LIMIT 1
`

// Returns the (single) role=context message in a Context. Each Context has at
// most one such message; APPEND-mode compression reads it to chain forward.
func (q *Queries) GetContextRoleMessageInContext(ctx context.Context, contextID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getContextRoleMessageInContext, contextID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}

const getLatestAssistantMessage = `-- name: GetLatestAssistantMessage :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers FROM messages
WHERE context_id = $1 AND role = 'assistant'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// Newest assistant turn in a context — the transcript seed for
// client-invoked title generation (GenerateConversationTitle).
func (q *Queries) GetLatestAssistantMessage(ctx context.Context, contextID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getLatestAssistantMessage, contextID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}

const getLatestMessageID = `-- name: GetLatestMessageID :one
SELECT id FROM messages
WHERE context_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The chronological tip of a context — resolveParent's fallback when
// no cursor is tracked. Only the id is needed; the previous
// implementation listed the ENTIRE context (embeddings included) to
// take the last element.
func (q *Queries) GetLatestMessageID(ctx context.Context, contextID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestMessageID, contextID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}

const hasCompressionSummaryInContext = `-- name: HasCompressionSummaryInContext :one
SELECT EXISTS(
    SELECT 1 FROM messages
    WHERE context_id = $1
      AND role = 'compression_summary'
      AND error_payload IS NULL
)::BOOLEAN AS has_summary
`

// True iff the context contains at least one role=compression_summary row that
// did NOT fail (error_payload IS NULL). SendMessage / Compact use this as a
// precondition: a clean pending summary must be promoted
// (PromoteCompactionToNewContext) or deleted (DeleteMessage) before more turns
// can land. Errored compression_summary rows are first-class history entries
// the user can review; they do not gate the conversation — the user retries
// by either deleting the failed summary or kicking off a fresh compaction.
func (q *Queries) HasCompressionSummaryInContext(ctx context.Context, contextID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasCompressionSummaryInContext, contextID)
	var has_summary bool
	err := row.Scan(&has_summary)
	return has_summary, err
}

const listContextLeafIDs = `-- name: ListContextLeafIDs :many
SELECT m.id FROM messages m
WHERE m.context_id = $1
  AND NOT EXISTS (SELECT 1 FROM messages c WHERE c.parent_id = m.id)
ORDER BY m.id DESC
LIMIT 2
`

// Ids of childless messages in a context, capped at 2 — history
// assembly only needs "none / exactly one / ambiguous" to preserve
// its leafless-Build contract without listing the whole context.
func (q *Queries) ListContextLeafIDs(ctx context.Context, contextID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listContextLeafIDs, contextID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageAncestorChain = `-- name: ListMessageAncestorChain :many
WITH RECURSIVE chain AS (
    SELECT messages.id, messages.context_id, messages.parent_id, messages.role, messages.content, messages.raw_content, messages.thinking, messages.thinking_provider_type, messages.thinking_rendered_text, messages.provider_id, messages.model_id, messages.created_at, messages.input_tokens, messages.output_tokens, messages.cache_read_tokens, messages.cache_write_tokens, messages.reasoning_tokens, messages.provider_usage_raw, messages.input_cost_usd, messages.output_cost_usd, messages.cache_read_cost_usd, messages.cache_write_cost_usd, messages.total_cost_usd, messages.edited_at, messages.error_payload, messages.thinking_duration_ms, messages.explicit_cache_attached, messages.tool_calls, messages.finish_reason, messages.tool_cost_usd, messages.is_welcome, messages.embedding, messages.embedding_model, messages.embedding_at, messages.message_headers, messages.message_trailers, 0 AS depth
    FROM messages
    WHERE messages.id = $1
    UNION ALL
    SELECT m.id, m.context_id, m.parent_id, m.role, m.content, m.raw_content, m.thinking, m.thinking_provider_type, m.thinking_rendered_text, m.provider_id, m.model_id, m.created_at, m.input_tokens, m.output_tokens, m.cache_read_tokens, m.cache_write_tokens, m.reasoning_tokens, m.provider_usage_raw, m.input_cost_usd, m.output_cost_usd, m.cache_read_cost_usd, m.cache_write_cost_usd, m.total_cost_usd, m.edited_at, m.error_payload, m.thinking_duration_ms, m.explicit_cache_attached, m.tool_calls, m.finish_reason, m.tool_cost_usd, m.is_welcome, m.embedding, m.embedding_model, m.embedding_at, m.message_headers, m.message_trailers, c.depth + 1
    FROM messages m
    INNER JOIN chain c ON m.id = c.parent_id
)
SELECT chain.id, chain.context_id, chain.parent_id, chain.role, chain.content,
       chain.raw_content, chain.thinking, chain.thinking_provider_type, chain.thinking_rendered_text,
       chain.thinking_duration_ms,
       chain.provider_id, chain.model_id,
       chain.input_tokens, chain.output_tokens, chain.cache_read_tokens, chain.cache_write_tokens,
       chain.reasoning_tokens, chain.provider_usage_raw,
       chain.input_cost_usd, chain.output_cost_usd, chain.cache_read_cost_usd, chain.cache_write_cost_usd,
       chain.tool_cost_usd,
       chain.total_cost_usd,
       chain.error_payload,
       chain.tool_calls,
       chain.finish_reason,
       chain.created_at,
       chain.edited_at,
       (
           SELECT COUNT(*)::INT FROM messages m
           WHERE m.id <> chain.id
             AND (
                 (chain.parent_id IS NOT NULL AND m.parent_id = chain.parent_id)
                 OR (chain.parent_id IS NULL AND m.context_id = chain.context_id AND m.parent_id IS NULL)
             )
       )::INT AS sibling_count
FROM chain
ORDER BY depth DESC
`

type ListMessageAncestorChainRow struct {
	ID                   uuid.UUID
	ContextID            uuid.UUID
	ParentID             *uuid.UUID
	Role                 string
	Content              string
	RawContent           *string
	Thinking             []byte
	ThinkingProviderType *string
	ThinkingRenderedText *string
	ThinkingDurationMs   *int32
	ProviderID           *uuid.UUID
	ModelID              *string
	InputTokens          *int32
	OutputTokens         *int32
	CacheReadTokens      *int32
	CacheWriteTokens     *int32
	ReasoningTokens      *int32
	ProviderUsageRaw     []byte
	InputCostUsd         pgtype.Numeric
	OutputCostUsd        pgtype.Numeric
	CacheReadCostUsd     pgtype.Numeric
	CacheWriteCostUsd    pgtype.Numeric
	ToolCostUsd          pgtype.Numeric
	TotalCostUsd         pgtype.Numeric
	ErrorPayload         []byte
	ToolCalls            []byte
	FinishReason         *string
	CreatedAt            time.Time
	EditedAt             *time.Time
	SiblingCount         int32
}

// Walks parent_id from the leaf back to the root, returning rows root-first.
// sibling_count: number of OTHER messages sharing this row's parent — i.e.
// branches forking off the same parent. The UI uses it to render fork
// indicators alongside the linear chain.
func (q *Queries) ListMessageAncestorChain(ctx context.Context, id uuid.UUID) ([]ListMessageAncestorChainRow, error) {
	rows, err := q.db.Query(ctx, listMessageAncestorChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageAncestorChainRow
	for rows.Next() {
		var i ListMessageAncestorChainRow
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.ParentID,
			&i.Role,
			&i.Content,
			&i.RawContent,
			&i.Thinking,
			&i.ThinkingProviderType,
			&i.ThinkingRenderedText,
			&i.ThinkingDurationMs,
			&i.ProviderID,
			&i.ModelID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.ReasoningTokens,
			&i.ProviderUsageRaw,
			&i.InputCostUsd,
			&i.OutputCostUsd,
			&i.CacheReadCostUsd,
			&i.CacheWriteCostUsd,
			&i.ToolCostUsd,
			&i.TotalCostUsd,
			&i.ErrorPayload,
			&i.ToolCalls,
			&i.FinishReason,
			&i.CreatedAt,
			&i.EditedAt,
			&i.SiblingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageChainForHistory = `-- name: ListMessageChainForHistory :many
WITH RECURSIVE chain AS (
    SELECT m.id, m.parent_id, 0 AS depth
    FROM messages m
    WHERE m.id = $1
    UNION ALL
    SELECT p.id, p.parent_id, chain.depth + 1
    FROM messages p
    JOIN chain ON chain.parent_id = p.id
)
SELECT messages.id, messages.context_id, messages.parent_id, messages.role, messages.content, messages.raw_content, messages.thinking, messages.thinking_provider_type, messages.thinking_rendered_text, messages.provider_id, messages.model_id, messages.created_at, messages.input_tokens, messages.output_tokens, messages.cache_read_tokens, messages.cache_write_tokens, messages.reasoning_tokens, messages.provider_usage_raw, messages.input_cost_usd, messages.output_cost_usd, messages.cache_read_cost_usd, messages.cache_write_cost_usd, messages.total_cost_usd, messages.edited_at, messages.error_payload, messages.thinking_duration_ms, messages.explicit_cache_attached, messages.tool_calls, messages.finish_reason, messages.tool_cost_usd, messages.is_welcome, messages.embedding, messages.embedding_model, messages.embedding_at, messages.message_headers, messages.message_trailers
FROM messages
JOIN chain ON chain.id = messages.id
ORDER BY chain.depth DESC
`

type ListMessageChainForHistoryRow struct {
	Message Message
}

// The ancestor chain of a leaf as FULL message rows (message_headers /
// message_trailers included — the wire envelope needs them), returned
// root-first. History assembly runs on every send and every token
// count; this is O(chain) where ListMessagesByContext is O(context),
// and forked contexts carry dead branches the chain never touches.
func (q *Queries) ListMessageChainForHistory(ctx context.Context, id uuid.UUID) ([]ListMessageChainForHistoryRow, error) {
	rows, err := q.db.Query(ctx, listMessageChainForHistory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageChainForHistoryRow
	for rows.Next() {
		var i ListMessageChainForHistoryRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.ContextID,
			&i.Message.ParentID,
			&i.Message.Role,
			&i.Message.Content,
			&i.Message.RawContent,
			&i.Message.Thinking,
			&i.Message.ThinkingProviderType,
			&i.Message.ThinkingRenderedText,
			&i.Message.ProviderID,
			&i.Message.ModelID,
			&i.Message.CreatedAt,
			&i.Message.InputTokens,
			&i.Message.OutputTokens,
			&i.Message.CacheReadTokens,
			&i.Message.CacheWriteTokens,
			&i.Message.ReasoningTokens,
			&i.Message.ProviderUsageRaw,
			&i.Message.InputCostUsd,
			&i.Message.OutputCostUsd,
			&i.Message.CacheReadCostUsd,
			&i.Message.CacheWriteCostUsd,
			&i.Message.TotalCostUsd,
			&i.Message.EditedAt,
			&i.Message.ErrorPayload,
			&i.Message.ThinkingDurationMs,
			&i.Message.ExplicitCacheAttached,
			&i.Message.ToolCalls,
			&i.Message.FinishReason,
			&i.Message.ToolCostUsd,
			&i.Message.IsWelcome,
			&i.Message.Embedding,
			&i.Message.EmbeddingModel,
			&i.Message.EmbeddingAt,
			&i.Message.MessageHeaders,
			&i.Message.MessageTrailers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageTreeStructure = `-- name: ListMessageTreeStructure :many
SELECT id, context_id, parent_id, role, created_at
FROM messages
WHERE context_id = $1
ORDER BY created_at ASC, id ASC
`

type ListMessageTreeStructureRow struct {
	ID        uuid.UUID
	ContextID uuid.UUID
	ParentID  *uuid.UUID
	Role      string
	CreatedAt time.Time
}

// Skeleton rows for the branch switcher: the tree SHAPE without
// content. Selecting only these columns keeps TOASTed message bodies
// entirely unread.
func (q *Queries) ListMessageTreeStructure(ctx context.Context, contextID uuid.UUID) ([]ListMessageTreeStructureRow, error) {
	rows, err := q.db.Query(ctx, listMessageTreeStructure, contextID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageTreeStructureRow
	for rows.Next() {
		var i ListMessageTreeStructureRow
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.ParentID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByContext = `-- name: ListMessagesByContext :many
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers FROM messages
WHERE context_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListMessagesByContext(ctx context.Context, contextID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByContext, contextID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.ParentID,
			&i.Role,
			&i.Content,
			&i.RawContent,
			&i.Thinking,
			&i.ThinkingProviderType,
			&i.ThinkingRenderedText,
			&i.ProviderID,
			&i.ModelID,
			&i.CreatedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.ReasoningTokens,
			&i.ProviderUsageRaw,
			&i.InputCostUsd,
			&i.OutputCostUsd,
			&i.CacheReadCostUsd,
			&i.CacheWriteCostUsd,
			&i.TotalCostUsd,
			&i.EditedAt,
			&i.ErrorPayload,
			&i.ThinkingDurationMs,
			&i.ExplicitCacheAttached,
			&i.ToolCalls,
			&i.FinishReason,
			&i.ToolCostUsd,
			&i.IsWelcome,
			&i.Embedding,
			&i.EmbeddingModel,
			&i.EmbeddingAt,
			&i.MessageHeaders,
			&i.MessageTrailers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesEmbeddedUnderDifferentModel = `-- name: ListMessagesEmbeddedUnderDifferentModel :many
SELECT id, content
FROM messages
WHERE embedding IS NOT NULL
  AND embedding_model <> $1
  AND role IN ('user', 'assistant', 'context')
  AND content <> ''
ORDER BY created_at ASC
LIMIT $2
`

type ListMessagesEmbeddedUnderDifferentModelParams struct {
	EmbeddingModel *string
	Limit          int32
}

type ListMessagesEmbeddedUnderDifferentModelRow struct {
	ID      uuid.UUID
	Content string
}

// When the user swaps embedders (different Model() than what's on
// existing rows), backfill re-embeds. Returns the rows that need
// re-embedding under the new model. Like ListUnembeddedMessages but
// the predicate is "wrong model" rather than "no embedding."
func (q *Queries) ListMessagesEmbeddedUnderDifferentModel(ctx context.Context, arg ListMessagesEmbeddedUnderDifferentModelParams) ([]ListMessagesEmbeddedUnderDifferentModelRow, error) {
	rows, err := q.db.Query(ctx, listMessagesEmbeddedUnderDifferentModel, arg.EmbeddingModel, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesEmbeddedUnderDifferentModelRow
	for rows.Next() {
		var i ListMessagesEmbeddedUnderDifferentModelRow
		if err := rows.Scan(&i.ID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnembeddedMessages = `-- name: ListUnembeddedMessages :many
SELECT m.id, m.content, c.user_id
FROM messages m
JOIN contexts ctx ON ctx.id = m.context_id
JOIN conversations c ON c.id = ctx.conversation_id
WHERE m.embedding IS NULL
  AND m.role IN ('user', 'assistant', 'context')
  AND m.content <> ''
ORDER BY c.user_id, m.created_at ASC
LIMIT $1
`

type ListUnembeddedMessagesRow struct {
	ID      uuid.UUID
	Content string
	UserID  uuid.UUID
}

// Backfill worker's hot path. Skips system messages (framing, not
// searchable content) and zero-length rows (nothing to embed). Ordered
// by user_id (so the worker can group within a batch and dispatch one
// embedder call per user) then oldest-first within the user — partial
// backfill makes monotonic progress against `created_at` and the
// "embedded up to YYYY-MM-DD" chip stays accurate.
func (q *Queries) ListUnembeddedMessages(ctx context.Context, limit int32) ([]ListUnembeddedMessagesRow, error) {
	rows, err := q.db.Query(ctx, listUnembeddedMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnembeddedMessagesRow
	for rows.Next() {
		var i ListUnembeddedMessagesRow
		if err := rows.Scan(&i.ID, &i.Content, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reparentChildren = `-- name: ReparentChildren :exec
UPDATE messages
SET parent_id = $2
WHERE parent_id = $1
`

type ReparentChildrenParams struct {
	ParentID   *uuid.UUID
	ParentID_2 *uuid.UUID
}

// Promotes every direct child of $1 to point at $2 (which may be NULL — that
// makes them roots in the context). Used by DeleteMessage(cascade=false) just
// before the DELETE, so the FK's ON DELETE CASCADE has nothing to find.
func (q *Queries) ReparentChildren(ctx context.Context, arg ReparentChildrenParams) error {
	_, err := q.db.Exec(ctx, reparentChildren, arg.ParentID, arg.ParentID_2)
	return err
}

const searchMessagesByEmbedding = `-- name: SearchMessagesByEmbedding :many
SELECT m.id,
       m.context_id,
       m.parent_id,
       m.role,
       m.content,
       m.created_at,
       ctx.conversation_id,
       c.title AS conversation_title,
       (m.embedding <=> $1)::FLOAT8 AS distance
FROM messages m
JOIN contexts ctx ON ctx.id = m.context_id
JOIN conversations c ON c.id = ctx.conversation_id
WHERE c.user_id = $2
  AND m.embedding_model = $3
  AND m.embedding IS NOT NULL
ORDER BY m.embedding <=> $1
LIMIT $4
`

type SearchMessagesByEmbeddingParams struct {
	Embedding      *pgvector.Vector
	UserID         uuid.UUID
	EmbeddingModel *string
	Limit          int32
}

type SearchMessagesByEmbeddingRow struct {
	ID                uuid.UUID
	ContextID         uuid.UUID
	ParentID          *uuid.UUID
	Role              string
	Content           string
	CreatedAt         time.Time
	ConversationID    uuid.UUID
	ConversationTitle *string
	Distance          float64
}

// Cosine-distance ranked search. Restricts to messages owned by the
// caller (via the context→conversation→user chain) and to rows
// embedded under the same model as the query vector — mixing models
// would compare vectors from different spaces and yield garbage.
//
// Returns m.context_id alongside m.id so the memory plugin can drop
// hits that are still in the wire prefix. A conversation is a
// SEQUENCE of contexts: when compression fires, the old context is
// retired and a new one becomes active. The wire prefix is only ever
// built from the active context, so messages from old contexts —
// even in the SAME conversation as the caller — are exactly the
// "no longer in scope" content the memory plugin should surface.
//
// `<=>` is pgvector's cosine-distance operator: 0 = identical
// direction, 2 = opposite. Smaller is better. We surface the raw
// distance so callers can threshold ("only return matches under 0.4").
//
// pgvector's HNSW index handles ORDER BY ... LIMIT efficiently even
// with the WHERE filter, provided the filter is selective enough to
// not prune away most candidates. For a single user that's free; if
// we ever scale to many users per Psmith instance the index would
// need partitioning, but that's a future-us problem.
func (q *Queries) SearchMessagesByEmbedding(ctx context.Context, arg SearchMessagesByEmbeddingParams) ([]SearchMessagesByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchMessagesByEmbedding,
		arg.Embedding,
		arg.UserID,
		arg.EmbeddingModel,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesByEmbeddingRow
	for rows.Next() {
		var i SearchMessagesByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.ParentID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.ConversationID,
			&i.ConversationTitle,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMessageEmbedding = `-- name: SetMessageEmbedding :exec
UPDATE messages
SET embedding       = $2,
    embedding_model = $3,
    embedding_at    = $4
WHERE id = $1
`

type SetMessageEmbeddingParams struct {
	ID             uuid.UUID
	Embedding      *pgvector.Vector
	EmbeddingModel *string
	EmbeddingAt    *time.Time
}

// Worker writes the embedding triple. Idempotent: the CHECK constraint
// enforces all-three-or-none on every row already, so calling with the
// same triple over and over is fine.
func (q *Queries) SetMessageEmbedding(ctx context.Context, arg SetMessageEmbeddingParams) error {
	_, err := q.db.Exec(ctx, setMessageEmbedding,
		arg.ID,
		arg.Embedding,
		arg.EmbeddingModel,
		arg.EmbeddingAt,
	)
	return err
}

const updateMessageContentRole = `-- name: UpdateMessageContentRole :one
UPDATE messages
SET content   = $2,
    role      = COALESCE($3, role),
    edited_at = NOW()
WHERE id = $1
RETURNING id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd, is_welcome, embedding, embedding_model, embedding_at, message_headers, message_trailers
`

type UpdateMessageContentRoleParams struct {
	ID      uuid.UUID
	Content string
	Role    *string
}

// In-place edit. content is always set; role is COALESCE'd so the caller can
// pass NULL to leave it unchanged. edited_at = NOW() unconditionally.
// sqlc.narg lets the role param be nullable (sqlc otherwise infers
// non-nullable from the column type).
func (q *Queries) UpdateMessageContentRole(ctx context.Context, arg UpdateMessageContentRoleParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContentRole, arg.ID, arg.Content, arg.Role)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
		&i.IsWelcome,
		&i.Embedding,
		&i.EmbeddingModel,
		&i.EmbeddingAt,
		&i.MessageHeaders,
		&i.MessageTrailers,
	)
	return i, err
}
