// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, client_label, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash   string
	UserID      uuid.UUID
	ClientLabel *string
	ExpiresAt   time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ClientLabel,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.token_hash,
    s.user_id,
    s.client_label,
    s.created_at AS session_created_at,
    s.last_used_at,
    s.expires_at,
    u.id              AS user_id_full,
    u.username        AS username,
    u.display_name    AS display_name,
    u.password_hash   AS password_hash,
    u.is_admin        AS is_admin,
    u.created_at      AS user_created_at,
    u.updated_at      AS user_updated_at
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token_hash = $1 AND s.expires_at > NOW()
`

type GetSessionWithUserRow struct {
	TokenHash        string
	UserID           uuid.UUID
	ClientLabel      *string
	SessionCreatedAt time.Time
	LastUsedAt       time.Time
	ExpiresAt        time.Time
	UserIDFull       uuid.UUID
	Username         string
	DisplayName      *string
	PasswordHash     string
	IsAdmin          bool
	UserCreatedAt    time.Time
	UserUpdatedAt    time.Time
}

func (q *Queries) GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, tokenHash)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ClientLabel,
		&i.SessionCreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.UserIDFull,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = NOW() WHERE token_hash = $1
`

func (q *Queries) TouchSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchSession, tokenHash)
	return err
}
