// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_models.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserModel = `-- name: DeleteUserModel :exec
DELETE FROM user_models
WHERE user_model_provider_id = $1 AND model_id = $2
`

type DeleteUserModelParams struct {
	UserModelProviderID uuid.UUID
	ModelID             string
}

func (q *Queries) DeleteUserModel(ctx context.Context, arg DeleteUserModelParams) error {
	_, err := q.db.Exec(ctx, deleteUserModel, arg.UserModelProviderID, arg.ModelID)
	return err
}

const getUserModel = `-- name: GetUserModel :one
SELECT user_model_provider_id, model_id, display_name, context_window, max_output_tokens, input_price_per_million, output_price_per_million, cache_read_per_million, cache_write_per_million, knowledge_cutoff, modalities, capabilities, default_settings, metadata_source, metadata_snapshot_at, enabled_at, favorite, pricing_tiers FROM user_models
WHERE user_model_provider_id = $1 AND model_id = $2
`

type GetUserModelParams struct {
	UserModelProviderID uuid.UUID
	ModelID             string
}

func (q *Queries) GetUserModel(ctx context.Context, arg GetUserModelParams) (UserModel, error) {
	row := q.db.QueryRow(ctx, getUserModel, arg.UserModelProviderID, arg.ModelID)
	var i UserModel
	err := row.Scan(
		&i.UserModelProviderID,
		&i.ModelID,
		&i.DisplayName,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.CacheReadPerMillion,
		&i.CacheWritePerMillion,
		&i.KnowledgeCutoff,
		&i.Modalities,
		&i.Capabilities,
		&i.DefaultSettings,
		&i.MetadataSource,
		&i.MetadataSnapshotAt,
		&i.EnabledAt,
		&i.Favorite,
		&i.PricingTiers,
	)
	return i, err
}

const listUserModelsByProvider = `-- name: ListUserModelsByProvider :many
SELECT user_model_provider_id, model_id, display_name, context_window, max_output_tokens, input_price_per_million, output_price_per_million, cache_read_per_million, cache_write_per_million, knowledge_cutoff, modalities, capabilities, default_settings, metadata_source, metadata_snapshot_at, enabled_at, favorite, pricing_tiers FROM user_models
WHERE user_model_provider_id = $1
ORDER BY model_id
`

func (q *Queries) ListUserModelsByProvider(ctx context.Context, userModelProviderID uuid.UUID) ([]UserModel, error) {
	rows, err := q.db.Query(ctx, listUserModelsByProvider, userModelProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserModel
	for rows.Next() {
		var i UserModel
		if err := rows.Scan(
			&i.UserModelProviderID,
			&i.ModelID,
			&i.DisplayName,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.InputPricePerMillion,
			&i.OutputPricePerMillion,
			&i.CacheReadPerMillion,
			&i.CacheWritePerMillion,
			&i.KnowledgeCutoff,
			&i.Modalities,
			&i.Capabilities,
			&i.DefaultSettings,
			&i.MetadataSource,
			&i.MetadataSnapshotAt,
			&i.EnabledAt,
			&i.Favorite,
			&i.PricingTiers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserModelsByUser = `-- name: ListUserModelsByUser :many
SELECT um.user_model_provider_id, um.model_id, um.display_name, um.context_window, um.max_output_tokens, um.input_price_per_million, um.output_price_per_million, um.cache_read_per_million, um.cache_write_per_million, um.knowledge_cutoff, um.modalities, um.capabilities, um.default_settings, um.metadata_source, um.metadata_snapshot_at, um.enabled_at, um.favorite, um.pricing_tiers
FROM user_models um
JOIN user_model_providers ump ON ump.id = um.user_model_provider_id
WHERE ump.user_id = $1
ORDER BY ump.created_at, um.model_id
`

func (q *Queries) ListUserModelsByUser(ctx context.Context, userID uuid.UUID) ([]UserModel, error) {
	rows, err := q.db.Query(ctx, listUserModelsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserModel
	for rows.Next() {
		var i UserModel
		if err := rows.Scan(
			&i.UserModelProviderID,
			&i.ModelID,
			&i.DisplayName,
			&i.ContextWindow,
			&i.MaxOutputTokens,
			&i.InputPricePerMillion,
			&i.OutputPricePerMillion,
			&i.CacheReadPerMillion,
			&i.CacheWritePerMillion,
			&i.KnowledgeCutoff,
			&i.Modalities,
			&i.Capabilities,
			&i.DefaultSettings,
			&i.MetadataSource,
			&i.MetadataSnapshotAt,
			&i.EnabledAt,
			&i.Favorite,
			&i.PricingTiers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserModelFavorite = `-- name: SetUserModelFavorite :exec
UPDATE user_models
SET favorite = $3
WHERE user_model_provider_id = $1 AND model_id = $2
`

type SetUserModelFavoriteParams struct {
	UserModelProviderID uuid.UUID
	ModelID             string
	Favorite            bool
}

func (q *Queries) SetUserModelFavorite(ctx context.Context, arg SetUserModelFavoriteParams) error {
	_, err := q.db.Exec(ctx, setUserModelFavorite, arg.UserModelProviderID, arg.ModelID, arg.Favorite)
	return err
}

const updateUserModelDefaultSettings = `-- name: UpdateUserModelDefaultSettings :exec
UPDATE user_models
SET default_settings = $3, metadata_snapshot_at = NOW()
WHERE user_model_provider_id = $1 AND model_id = $2
`

type UpdateUserModelDefaultSettingsParams struct {
	UserModelProviderID uuid.UUID
	ModelID             string
	DefaultSettings     []byte
}

// Replaces (not merges) the per-model default_settings JSONB blob. NULL
// clears it. metadata_snapshot_at is bumped so consumers polling for row
// changes notice the update — the row's metadata identity hasn't changed,
// but its effective behavior has.
func (q *Queries) UpdateUserModelDefaultSettings(ctx context.Context, arg UpdateUserModelDefaultSettingsParams) error {
	_, err := q.db.Exec(ctx, updateUserModelDefaultSettings, arg.UserModelProviderID, arg.ModelID, arg.DefaultSettings)
	return err
}

const upsertUserModel = `-- name: UpsertUserModel :one
INSERT INTO user_models (
    user_model_provider_id, model_id, display_name,
    context_window, max_output_tokens,
    input_price_per_million, output_price_per_million,
    cache_read_per_million, cache_write_per_million,
    knowledge_cutoff, modalities, capabilities, default_settings,
    metadata_source, metadata_snapshot_at, pricing_tiers
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (user_model_provider_id, model_id) DO UPDATE SET
    display_name              = EXCLUDED.display_name,
    context_window            = EXCLUDED.context_window,
    max_output_tokens         = EXCLUDED.max_output_tokens,
    input_price_per_million   = EXCLUDED.input_price_per_million,
    output_price_per_million  = EXCLUDED.output_price_per_million,
    cache_read_per_million    = EXCLUDED.cache_read_per_million,
    cache_write_per_million   = EXCLUDED.cache_write_per_million,
    knowledge_cutoff          = EXCLUDED.knowledge_cutoff,
    modalities                = EXCLUDED.modalities,
    capabilities              = EXCLUDED.capabilities,
    default_settings          = EXCLUDED.default_settings,
    metadata_source           = EXCLUDED.metadata_source,
    metadata_snapshot_at      = EXCLUDED.metadata_snapshot_at,
    pricing_tiers             = EXCLUDED.pricing_tiers
RETURNING user_model_provider_id, model_id, display_name, context_window, max_output_tokens, input_price_per_million, output_price_per_million, cache_read_per_million, cache_write_per_million, knowledge_cutoff, modalities, capabilities, default_settings, metadata_source, metadata_snapshot_at, enabled_at, favorite, pricing_tiers
`

type UpsertUserModelParams struct {
	UserModelProviderID   uuid.UUID
	ModelID               string
	DisplayName           string
	ContextWindow         *int32
	MaxOutputTokens       *int32
	InputPricePerMillion  *float64
	OutputPricePerMillion *float64
	CacheReadPerMillion   *float64
	CacheWritePerMillion  *float64
	KnowledgeCutoff       pgtype.Date
	Modalities            []string
	Capabilities          []byte
	DefaultSettings       []byte
	MetadataSource        string
	MetadataSnapshotAt    time.Time
	PricingTiers          []byte
}

func (q *Queries) UpsertUserModel(ctx context.Context, arg UpsertUserModelParams) (UserModel, error) {
	row := q.db.QueryRow(ctx, upsertUserModel,
		arg.UserModelProviderID,
		arg.ModelID,
		arg.DisplayName,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.InputPricePerMillion,
		arg.OutputPricePerMillion,
		arg.CacheReadPerMillion,
		arg.CacheWritePerMillion,
		arg.KnowledgeCutoff,
		arg.Modalities,
		arg.Capabilities,
		arg.DefaultSettings,
		arg.MetadataSource,
		arg.MetadataSnapshotAt,
		arg.PricingTiers,
	)
	var i UserModel
	err := row.Scan(
		&i.UserModelProviderID,
		&i.ModelID,
		&i.DisplayName,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.CacheReadPerMillion,
		&i.CacheWritePerMillion,
		&i.KnowledgeCutoff,
		&i.Modalities,
		&i.Capabilities,
		&i.DefaultSettings,
		&i.MetadataSource,
		&i.MetadataSnapshotAt,
		&i.EnabledAt,
		&i.Favorite,
		&i.PricingTiers,
	)
	return i, err
}
