// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_model_providers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUserModelProvider = `-- name: CreateUserModelProvider :one
INSERT INTO user_model_providers (id, user_id, type, label, config_encrypted, default_settings)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, type, label, config, created_at, updated_at, default_settings, config_encrypted
`

type CreateUserModelProviderParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Type            string
	Label           string
	ConfigEncrypted []byte
	DefaultSettings []byte
}

// config_encrypted is the AES-256-GCM-sealed JSONB blob; the legacy
// `config` column is left NULL. The service layer's Get/List path
// decrypts config_encrypted when present and falls back to plaintext
// config for any row that hasn't been touched since the encryption
// rollout.
func (q *Queries) CreateUserModelProvider(ctx context.Context, arg CreateUserModelProviderParams) (UserModelProvider, error) {
	row := q.db.QueryRow(ctx, createUserModelProvider,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Label,
		arg.ConfigEncrypted,
		arg.DefaultSettings,
	)
	var i UserModelProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultSettings,
		&i.ConfigEncrypted,
	)
	return i, err
}

const deleteUserModelProvider = `-- name: DeleteUserModelProvider :exec
DELETE FROM user_model_providers WHERE id = $1
`

func (q *Queries) DeleteUserModelProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserModelProvider, id)
	return err
}

const getUserModelProvider = `-- name: GetUserModelProvider :one
SELECT id, user_id, type, label, config, created_at, updated_at, default_settings, config_encrypted FROM user_model_providers WHERE id = $1
`

func (q *Queries) GetUserModelProvider(ctx context.Context, id uuid.UUID) (UserModelProvider, error) {
	row := q.db.QueryRow(ctx, getUserModelProvider, id)
	var i UserModelProvider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Label,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultSettings,
		&i.ConfigEncrypted,
	)
	return i, err
}

const listUserModelProvidersByUser = `-- name: ListUserModelProvidersByUser :many
SELECT id, user_id, type, label, config, created_at, updated_at, default_settings, config_encrypted FROM user_model_providers
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListUserModelProvidersByUser(ctx context.Context, userID uuid.UUID) ([]UserModelProvider, error) {
	rows, err := q.db.Query(ctx, listUserModelProvidersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserModelProvider
	for rows.Next() {
		var i UserModelProvider
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Label,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DefaultSettings,
			&i.ConfigEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserModelProviderDefaultSettings = `-- name: UpdateUserModelProviderDefaultSettings :exec
UPDATE user_model_providers
SET default_settings = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserModelProviderDefaultSettingsParams struct {
	ID              uuid.UUID
	DefaultSettings []byte
}

// Replaces (not merges) the provider-level default_settings blob. NULL clears
// it, returning the row to "no provider-level defaults; resolve from above
// only." Replace semantics keep the call site simple — the resolver does the
// merge with the upper layers, so partial writes here would be a footgun.
func (q *Queries) UpdateUserModelProviderDefaultSettings(ctx context.Context, arg UpdateUserModelProviderDefaultSettingsParams) error {
	_, err := q.db.Exec(ctx, updateUserModelProviderDefaultSettings, arg.ID, arg.DefaultSettings)
	return err
}

const updateUserModelProviderEncryptedConfig = `-- name: UpdateUserModelProviderEncryptedConfig :exec
UPDATE user_model_providers
SET config_encrypted = $2, config = NULL, updated_at = NOW()
WHERE id = $1
`

type UpdateUserModelProviderEncryptedConfigParams struct {
	ID              uuid.UUID
	ConfigEncrypted []byte
}

// Full-replacement update on the encrypted column. The service layer
// handles partial-merge semantics in Go (decrypt → JSON merge →
// re-encrypt) before calling this — the SQL side stays straightforward
// replacement so the encrypted bytes remain a single sealed unit.
// Clears any plaintext config that may still be present, finalising
// the row's transition to encrypted-only storage.
func (q *Queries) UpdateUserModelProviderEncryptedConfig(ctx context.Context, arg UpdateUserModelProviderEncryptedConfigParams) error {
	_, err := q.db.Exec(ctx, updateUserModelProviderEncryptedConfig, arg.ID, arg.ConfigEncrypted)
	return err
}

const updateUserModelProviderLabel = `-- name: UpdateUserModelProviderLabel :exec
UPDATE user_model_providers
SET label = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserModelProviderLabelParams struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) UpdateUserModelProviderLabel(ctx context.Context, arg UpdateUserModelProviderLabelParams) error {
	_, err := q.db.Exec(ctx, updateUserModelProviderLabel, arg.ID, arg.Label)
	return err
}
