// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_langfuse_config.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserLangfuseConfig = `-- name: DeleteUserLangfuseConfig :exec
DELETE FROM user_langfuse_config WHERE user_id = $1
`

// Removes the entire row. Drops both credentials and the enabled
// toggle in one shot — for users who want to fully sever the
// integration rather than just disable it.
func (q *Queries) DeleteUserLangfuseConfig(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserLangfuseConfig, userID)
	return err
}

const getUserLangfuseConfig = `-- name: GetUserLangfuseConfig :one
SELECT user_id, host, public_key, secret_key_encrypted, enabled, created_at, updated_at FROM user_langfuse_config
WHERE user_id = $1
`

// Returns the user's Langfuse config row, if any. pgx ErrNoRows on
// absent — service layer maps that to "tracing disabled" rather than
// a hard error so the GET RPC can return the default-disabled shape.
func (q *Queries) GetUserLangfuseConfig(ctx context.Context, userID uuid.UUID) (UserLangfuseConfig, error) {
	row := q.db.QueryRow(ctx, getUserLangfuseConfig, userID)
	var i UserLangfuseConfig
	err := row.Scan(
		&i.UserID,
		&i.Host,
		&i.PublicKey,
		&i.SecretKeyEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserLangfuseConfigs = `-- name: ListUserLangfuseConfigs :many
SELECT user_id, host, public_key, secret_key_encrypted, enabled, created_at, updated_at FROM user_langfuse_config ORDER BY user_id
`

// Every existing row across all users. Used at server boot to prime
// the in-memory emitter cache so tracing works for the very first
// assistant turn after a restart, not just after the first
// LangfuseService.Update RPC of the new process.
func (q *Queries) ListUserLangfuseConfigs(ctx context.Context) ([]UserLangfuseConfig, error) {
	rows, err := q.db.Query(ctx, listUserLangfuseConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserLangfuseConfig
	for rows.Next() {
		var i UserLangfuseConfig
		if err := rows.Scan(
			&i.UserID,
			&i.Host,
			&i.PublicKey,
			&i.SecretKeyEncrypted,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserLangfuseConfig = `-- name: UpsertUserLangfuseConfig :one
INSERT INTO user_langfuse_config (
    user_id, host, public_key, secret_key_encrypted, enabled, updated_at
) VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (user_id) DO UPDATE SET
    host                 = EXCLUDED.host,
    public_key           = EXCLUDED.public_key,
    secret_key_encrypted = EXCLUDED.secret_key_encrypted,
    enabled              = EXCLUDED.enabled,
    updated_at           = NOW()
RETURNING user_id, host, public_key, secret_key_encrypted, enabled, created_at, updated_at
`

type UpsertUserLangfuseConfigParams struct {
	UserID             uuid.UUID
	Host               string
	PublicKey          string
	SecretKeyEncrypted []byte
	Enabled            bool
}

// Single-call full replace. The service layer reads the existing row
// (if any), merges request fields onto it, then calls this — same
// pattern as UpdateUserModel. secret_key_encrypted is the only
// credential column; the value is AES-GCM encrypted before it
// reaches this query (see internal/langfusesvc).
func (q *Queries) UpsertUserLangfuseConfig(ctx context.Context, arg UpsertUserLangfuseConfigParams) (UserLangfuseConfig, error) {
	row := q.db.QueryRow(ctx, upsertUserLangfuseConfig,
		arg.UserID,
		arg.Host,
		arg.PublicKey,
		arg.SecretKeyEncrypted,
		arg.Enabled,
	)
	var i UserLangfuseConfig
	err := row.Scan(
		&i.UserID,
		&i.Host,
		&i.PublicKey,
		&i.SecretKeyEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
