// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_mcp_servers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserMCPServer = `-- name: DeleteUserMCPServer :execrows
DELETE FROM user_mcp_servers
WHERE id = $1 AND user_id = $2
`

type DeleteUserMCPServerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUserMCPServer(ctx context.Context, arg DeleteUserMCPServerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserMCPServer, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserMCPServer = `-- name: GetUserMCPServer :one
SELECT id, user_id, name, config, config_encrypted, created_at, updated_at FROM user_mcp_servers
WHERE id = $1
`

func (q *Queries) GetUserMCPServer(ctx context.Context, id uuid.UUID) (UserMcpServer, error) {
	row := q.db.QueryRow(ctx, getUserMCPServer, id)
	var i UserMcpServer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Config,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUserMCPServer = `-- name: InsertUserMCPServer :one
INSERT INTO user_mcp_servers (id, user_id, name, config_encrypted)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, config, config_encrypted, created_at, updated_at
`

type InsertUserMCPServerParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Name            string
	ConfigEncrypted []byte
}

func (q *Queries) InsertUserMCPServer(ctx context.Context, arg InsertUserMCPServerParams) (UserMcpServer, error) {
	row := q.db.QueryRow(ctx, insertUserMCPServer,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ConfigEncrypted,
	)
	var i UserMcpServer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Config,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserMCPServers = `-- name: ListUserMCPServers :many
SELECT id, user_id, name, config, config_encrypted, created_at, updated_at FROM user_mcp_servers
WHERE user_id = $1
ORDER BY name, id
`

func (q *Queries) ListUserMCPServers(ctx context.Context, userID uuid.UUID) ([]UserMcpServer, error) {
	rows, err := q.db.Query(ctx, listUserMCPServers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserMcpServer
	for rows.Next() {
		var i UserMcpServer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Config,
			&i.ConfigEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserMCPServer = `-- name: UpdateUserMCPServer :one
UPDATE user_mcp_servers
SET name = $3,
    config = NULL,
    config_encrypted = $4,
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, config, config_encrypted, created_at, updated_at
`

type UpdateUserMCPServerParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Name            string
	ConfigEncrypted []byte
}

func (q *Queries) UpdateUserMCPServer(ctx context.Context, arg UpdateUserMCPServerParams) (UserMcpServer, error) {
	row := q.db.QueryRow(ctx, updateUserMCPServer,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.ConfigEncrypted,
	)
	var i UserMcpServer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Config,
		&i.ConfigEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
