package plugins

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// ImagegenName is the registered name for the OpenAI image-gen tool plugin.
const ImagegenName = "imagegen"

const (
	imagegenDefaultEndpoint = "https://api.openai.com/v1/images/generations"
	imagegenDefaultModel    = "gpt-image-1"
	imagegenDefaultSize     = "1024x1024"
	imagegenDefaultQuality  = "high"
	imagegenDefaultTimeout  = 60 * time.Second
)

// imagegen declares one tool — `generate_image` — that the model can call to
// produce an image from a text prompt. Implements ToolProvider + Configurable.
//
// Backed by OpenAI's `/v1/images/generations` endpoint (gpt-image-1 by
// default; dall-e-3 supported via config). The generated bytes come back
// base64-encoded and ride through the existing tool-result attachment
// pipeline — they get persisted on the assistant message with
// role_hint=tool_result, render in the chat surface as an image
// attachment, and (for drivers that support image-in-tool-result)
// flow back into the next-round wire prefix so the model can
// reference what it just generated.
type imagegen struct {
	cfg    imagegenConfig
	client *http.Client
}

// imagegenConfig is the per-instance config. APIKey is required.
type imagegenConfig struct {
	// APIKey is the OpenAI API key. Sent as `Authorization: Bearer
	// <key>` on every request. Required. Plugins ship this in their
	// own config rather than reading from the chat model_provider
	// row so an image-only OpenAI key (e.g. a workspace key with
	// images-only billing) can be different from the chat key.
	APIKey string `json:"api_key"`

	// Model picks the OpenAI image model. Defaults to "gpt-image-1"
	// (the modern endpoint); "dall-e-3" still works. Other models
	// pass through verbatim — OpenAI's API surface accepts whatever
	// the account has access to.
	Model string `json:"model"`

	// Size is the default rendered size when the model doesn't
	// specify one. Common values for gpt-image-1: "1024x1024"
	// (square), "1024x1536" (portrait), "1536x1024" (landscape),
	// or "auto" (model picks). Defaults to "1024x1024".
	Size string `json:"size"`

	// Quality maps to OpenAI's `quality` parameter. For gpt-image-1:
	// "low", "medium", "high", "auto". For dall-e-3: "standard" or
	// "hd". Defaults to "high".
	Quality string `json:"quality"`

	// EndpointOverride lets test harnesses point the plugin at a
	// fake. Empty = production OpenAI endpoint.
	EndpointOverride string `json:"endpoint_override"`
}

// imagegenInput is the JSON Schema-described input the model passes
// on tool_use. Only `prompt` is required; size + quality are
// optional per-call overrides of the plugin's defaults.
type imagegenInput struct {
	Prompt  string `json:"prompt"`
	Size    string `json:"size,omitempty"`
	Quality string `json:"quality,omitempty"`
}

// imagegenAPIResponse is the subset of OpenAI's response we decode.
// gpt-image-1 always returns base64; dall-e-3 returns base64 when
// `response_format=b64_json` is requested (we always do).
type imagegenAPIResponse struct {
	Data []struct {
		B64JSON       string `json:"b64_json"`
		RevisedPrompt string `json:"revised_prompt,omitempty"`
	} `json:"data"`
	Error *struct {
		Message string `json:"message"`
		Type    string `json:"type"`
		Code    string `json:"code"`
	} `json:"error,omitempty"`
}

func newImagegen(configBytes json.RawMessage) (Plugin, error) {
	cfg := imagegenConfig{
		Model:   imagegenDefaultModel,
		Size:    imagegenDefaultSize,
		Quality: imagegenDefaultQuality,
	}
	if len(configBytes) > 0 {
		if err := json.Unmarshal(configBytes, &cfg); err != nil {
			return nil, fmt.Errorf("imagegen: parse config: %w", err)
		}
	}
	if cfg.Model == "" {
		cfg.Model = imagegenDefaultModel
	}
	if cfg.Size == "" {
		cfg.Size = imagegenDefaultSize
	}
	if cfg.Quality == "" {
		cfg.Quality = imagegenDefaultQuality
	}
	return &imagegen{
		cfg:    cfg,
		client: &http.Client{Timeout: imagegenDefaultTimeout},
	}, nil
}

func init() {
	Register(ImagegenName, newImagegen)
}

func (p *imagegen) Name() string        { return ImagegenName }
func (p *imagegen) DisplayName() string { return "Image Generation" }

func (p *imagegen) Description() string {
	return "Gives the model a generate_image tool backed by OpenAI's image API " +
		"(gpt-image-1 by default; dall-e-3 supported). Generated images attach " +
		"to the assistant turn that produced them and ride back into the next " +
		"round's wire prefix on providers that support image-in-tool-result, " +
		"so the model can iterate on what it just made. Requires an OpenAI API key."
}

// --- Configurable ---

func (p *imagegen) ConfigFields() []ConfigField {
	return []ConfigField{
		{
			Name:        "api_key",
			Display:     "OpenAI API key",
			Description: "Required. Used as `Authorization: Bearer <key>` on every image-gen request. May differ from your chat OpenAI key (e.g. an images-only workspace key).",
			Type:        ConfigFieldText,
		},
		{
			Name:        "model",
			Display:     "Model",
			Description: "OpenAI image model to call. Defaults to gpt-image-1 (modern); dall-e-3 still works.",
			Type:        ConfigFieldSelect,
			Default:     imagegenDefaultModel,
			Options: []ConfigOption{
				{Value: "gpt-image-1", Label: "gpt-image-1 (default)"},
				{Value: "dall-e-3", Label: "dall-e-3"},
			},
		},
		{
			Name:        "size",
			Display:     "Default size",
			Description: "Rendered size when the model doesn't specify one. \"auto\" lets the model pick.",
			Type:        ConfigFieldSelect,
			Default:     imagegenDefaultSize,
			Options: []ConfigOption{
				{Value: "1024x1024", Label: "1024×1024 (square)"},
				{Value: "1024x1536", Label: "1024×1536 (portrait)"},
				{Value: "1536x1024", Label: "1536×1024 (landscape)"},
				{Value: "auto", Label: "auto (model picks)"},
			},
		},
		{
			Name:        "quality",
			Display:     "Default quality",
			Description: "gpt-image-1: low / medium / high / auto. dall-e-3: standard / hd.",
			Type:        ConfigFieldSelect,
			Default:     imagegenDefaultQuality,
			Options: []ConfigOption{
				{Value: "low", Label: "low (gpt-image-1)"},
				{Value: "medium", Label: "medium (gpt-image-1)"},
				{Value: "high", Label: "high (gpt-image-1)"},
				{Value: "auto", Label: "auto"},
				{Value: "standard", Label: "standard (dall-e-3)"},
				{Value: "hd", Label: "hd (dall-e-3)"},
			},
		},
	}
}

// --- ToolProvider ---

func (p *imagegen) Tools() []ToolDef {
	schema := []byte(`{
  "type": "object",
  "properties": {
    "prompt": {
      "type": "string",
      "description": "Plain-language description of the image to generate. Be specific about subject, style, composition, and lighting — the model treats the prompt verbatim."
    },
    "size": {
      "type": "string",
      "description": "Optional size override. Common values: 1024x1024, 1024x1536, 1536x1024, auto.",
      "enum": ["1024x1024", "1024x1536", "1536x1024", "auto"]
    },
    "quality": {
      "type": "string",
      "description": "Optional quality override. gpt-image-1: low/medium/high/auto. dall-e-3: standard/hd.",
      "enum": ["low", "medium", "high", "auto", "standard", "hd"]
    }
  },
  "required": ["prompt"]
}`)
	return []ToolDef{
		{
			Name:        "generate_image",
			Description: "Generate an image from a text prompt. Returns the generated image as an attachment on this turn — the user sees it inline and you can reference it on the next round.",
			InputSchema: schema,
		},
	}
}

func (p *imagegen) ExecuteTool(ctx context.Context, name string, input json.RawMessage) (ToolResult, error) {
	if name != "generate_image" {
		return ToolResult{}, fmt.Errorf("imagegen: unknown tool %q", name)
	}
	if p.cfg.APIKey == "" {
		return ToolResult{}, fmt.Errorf("imagegen: api_key is not configured")
	}

	var in imagegenInput
	if err := json.Unmarshal(input, &in); err != nil {
		return ToolResult{}, fmt.Errorf("imagegen: parse input: %w", err)
	}
	in.Prompt = strings.TrimSpace(in.Prompt)
	if in.Prompt == "" {
		return ToolResult{}, fmt.Errorf("imagegen: prompt is required")
	}
	size := in.Size
	if size == "" {
		size = p.cfg.Size
	}
	quality := in.Quality
	if quality == "" {
		quality = p.cfg.Quality
	}

	endpoint := p.cfg.EndpointOverride
	if endpoint == "" {
		endpoint = imagegenDefaultEndpoint
	}

	body := map[string]any{
		"model":   p.cfg.Model,
		"prompt":  in.Prompt,
		"n":       1,
		"size":    size,
		"quality": quality,
	}
	// dall-e-3 requires `response_format: b64_json` to get base64;
	// gpt-image-1 returns base64 by default and rejects the field.
	// Send only when on dall-e-3.
	if p.cfg.Model == "dall-e-3" {
		body["response_format"] = "b64_json"
	}
	payload, err := json.Marshal(body)
	if err != nil {
		return ToolResult{}, fmt.Errorf("imagegen: encode body: %w", err)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, bytes.NewReader(payload))
	if err != nil {
		return ToolResult{}, fmt.Errorf("imagegen: build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+p.cfg.APIKey)

	resp, err := p.client.Do(req)
	if err != nil {
		return ToolResult{}, fmt.Errorf("imagegen: http call: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return ToolResult{}, fmt.Errorf("imagegen: read body: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		excerpt := string(respBody)
		if len(excerpt) > 240 {
			excerpt = excerpt[:240] + "…"
		}
		return ToolResult{}, fmt.Errorf("imagegen: %s — %s", resp.Status, excerpt)
	}

	var raw imagegenAPIResponse
	if err := json.Unmarshal(respBody, &raw); err != nil {
		return ToolResult{}, fmt.Errorf("imagegen: decode response: %w", err)
	}
	if raw.Error != nil && raw.Error.Message != "" {
		return ToolResult{}, fmt.Errorf("imagegen: %s", raw.Error.Message)
	}
	if len(raw.Data) == 0 {
		return ToolResult{}, fmt.Errorf("imagegen: empty data array in response")
	}
	first := raw.Data[0]
	if first.B64JSON == "" {
		return ToolResult{}, fmt.Errorf("imagegen: response missing b64_json")
	}
	imgBytes, err := base64.StdEncoding.DecodeString(first.B64JSON)
	if err != nil {
		return ToolResult{}, fmt.Errorf("imagegen: decode b64_json: %w", err)
	}

	// What the model sees on the next round: a small JSON envelope
	// summarising what was produced. The actual bytes flow via the
	// attachment, which (on Anthropic + Google) ride into the
	// next-round wire prefix as image content the model can
	// reference directly.
	out := map[string]any{
		"prompt":           in.Prompt,
		"size":             size,
		"quality":          quality,
		"model":            p.cfg.Model,
		"attachment_count": 1,
	}
	if first.RevisedPrompt != "" {
		out["revised_prompt"] = first.RevisedPrompt
	}
	encoded, err := json.Marshal(out)
	if err != nil {
		return ToolResult{}, fmt.Errorf("imagegen: encode output: %w", err)
	}

	return ToolResult{
		Output: encoded,
		Attachments: []ToolAttachment{{
			Kind:     "image",
			MimeType: "image/png",
			Data:     imgBytes,
			Filename: "generated.png",
		}},
	}, nil
}
