// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCatalogModels = `-- name: CountCatalogModels :one
SELECT COUNT(*) FROM catalog_models
`

func (q *Queries) CountCatalogModels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogModels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCatalogProviders = `-- name: CountCatalogProviders :one
SELECT COUNT(*) FROM catalog_model_providers
`

func (q *Queries) CountCatalogProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCatalogProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCatalogModel = `-- name: GetCatalogModel :one
SELECT provider_id, model_id, display_name, context_window, max_output_tokens, input_price_per_million, output_price_per_million, cache_read_per_million, cache_write_per_million, knowledge_cutoff, modalities, capabilities, raw, fetched_at FROM catalog_models WHERE provider_id = $1 AND model_id = $2
`

type GetCatalogModelParams struct {
	ProviderID string
	ModelID    string
}

func (q *Queries) GetCatalogModel(ctx context.Context, arg GetCatalogModelParams) (CatalogModel, error) {
	row := q.db.QueryRow(ctx, getCatalogModel, arg.ProviderID, arg.ModelID)
	var i CatalogModel
	err := row.Scan(
		&i.ProviderID,
		&i.ModelID,
		&i.DisplayName,
		&i.ContextWindow,
		&i.MaxOutputTokens,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.CacheReadPerMillion,
		&i.CacheWritePerMillion,
		&i.KnowledgeCutoff,
		&i.Modalities,
		&i.Capabilities,
		&i.Raw,
		&i.FetchedAt,
	)
	return i, err
}

const getCatalogProvider = `-- name: GetCatalogProvider :one
SELECT id, name, api_base, env_key, doc_url, npm, raw, fetched_at FROM catalog_model_providers WHERE id = $1
`

func (q *Queries) GetCatalogProvider(ctx context.Context, id string) (CatalogModelProvider, error) {
	row := q.db.QueryRow(ctx, getCatalogProvider, id)
	var i CatalogModelProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiBase,
		&i.EnvKey,
		&i.DocUrl,
		&i.Npm,
		&i.Raw,
		&i.FetchedAt,
	)
	return i, err
}

const latestCatalogFetch = `-- name: LatestCatalogFetch :one
SELECT MAX(fetched_at)::TIMESTAMPTZ AS latest FROM catalog_model_providers
`

func (q *Queries) LatestCatalogFetch(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestCatalogFetch)
	var latest time.Time
	err := row.Scan(&latest)
	return latest, err
}

const listCatalogProviders = `-- name: ListCatalogProviders :many
SELECT id, name, api_base, env_key, doc_url, npm, raw, fetched_at FROM catalog_model_providers ORDER BY id
`

func (q *Queries) ListCatalogProviders(ctx context.Context) ([]CatalogModelProvider, error) {
	rows, err := q.db.Query(ctx, listCatalogProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogModelProvider
	for rows.Next() {
		var i CatalogModelProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiBase,
			&i.EnvKey,
			&i.DocUrl,
			&i.Npm,
			&i.Raw,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCatalogModel = `-- name: UpsertCatalogModel :exec

INSERT INTO catalog_models (
    provider_id, model_id, display_name, context_window, max_output_tokens,
    input_price_per_million, output_price_per_million,
    cache_read_per_million, cache_write_per_million,
    knowledge_cutoff, modalities, capabilities, raw, fetched_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (provider_id, model_id) DO UPDATE SET
    display_name              = EXCLUDED.display_name,
    context_window            = EXCLUDED.context_window,
    max_output_tokens         = EXCLUDED.max_output_tokens,
    input_price_per_million   = EXCLUDED.input_price_per_million,
    output_price_per_million  = EXCLUDED.output_price_per_million,
    cache_read_per_million    = EXCLUDED.cache_read_per_million,
    cache_write_per_million   = EXCLUDED.cache_write_per_million,
    knowledge_cutoff          = EXCLUDED.knowledge_cutoff,
    modalities                = EXCLUDED.modalities,
    capabilities              = EXCLUDED.capabilities,
    raw                       = EXCLUDED.raw,
    fetched_at                = EXCLUDED.fetched_at
`

type UpsertCatalogModelParams struct {
	ProviderID            string
	ModelID               string
	DisplayName           string
	ContextWindow         *int32
	MaxOutputTokens       *int32
	InputPricePerMillion  *float64
	OutputPricePerMillion *float64
	CacheReadPerMillion   *float64
	CacheWritePerMillion  *float64
	KnowledgeCutoff       pgtype.Date
	Modalities            []string
	Capabilities          []byte
	Raw                   []byte
	FetchedAt             time.Time
}

// Catalog models -----------------------------------------------------------
func (q *Queries) UpsertCatalogModel(ctx context.Context, arg UpsertCatalogModelParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogModel,
		arg.ProviderID,
		arg.ModelID,
		arg.DisplayName,
		arg.ContextWindow,
		arg.MaxOutputTokens,
		arg.InputPricePerMillion,
		arg.OutputPricePerMillion,
		arg.CacheReadPerMillion,
		arg.CacheWritePerMillion,
		arg.KnowledgeCutoff,
		arg.Modalities,
		arg.Capabilities,
		arg.Raw,
		arg.FetchedAt,
	)
	return err
}

const upsertCatalogProvider = `-- name: UpsertCatalogProvider :exec

INSERT INTO catalog_model_providers (id, name, api_base, env_key, doc_url, npm, raw, fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    api_base   = EXCLUDED.api_base,
    env_key    = EXCLUDED.env_key,
    doc_url    = EXCLUDED.doc_url,
    npm        = EXCLUDED.npm,
    raw        = EXCLUDED.raw,
    fetched_at = EXCLUDED.fetched_at
`

type UpsertCatalogProviderParams struct {
	ID        string
	Name      string
	ApiBase   *string
	EnvKey    *string
	DocUrl    *string
	Npm       *string
	Raw       []byte
	FetchedAt time.Time
}

// Catalog providers --------------------------------------------------------
func (q *Queries) UpsertCatalogProvider(ctx context.Context, arg UpsertCatalogProviderParams) error {
	_, err := q.db.Exec(ctx, upsertCatalogProvider,
		arg.ID,
		arg.Name,
		arg.ApiBase,
		arg.EnvKey,
		arg.DocUrl,
		arg.Npm,
		arg.Raw,
		arg.FetchedAt,
	)
	return err
}
