// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contexts.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createContext = `-- name: CreateContext :one
INSERT INTO contexts (
    id, conversation_id, parent_context_id, context_activation_time
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, conversation_id, parent_context_id, context_activation_time, created_at, current_leaf_message_id, title
`

type CreateContextParams struct {
	ID                    uuid.UUID
	ConversationID        uuid.UUID
	ParentContextID       *uuid.UUID
	ContextActivationTime time.Time
}

func (q *Queries) CreateContext(ctx context.Context, arg CreateContextParams) (Context, error) {
	row := q.db.QueryRow(ctx, createContext,
		arg.ID,
		arg.ConversationID,
		arg.ParentContextID,
		arg.ContextActivationTime,
	)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ParentContextID,
		&i.ContextActivationTime,
		&i.CreatedAt,
		&i.CurrentLeafMessageID,
		&i.Title,
	)
	return i, err
}

const getActiveContextByConversation = `-- name: GetActiveContextByConversation :one
SELECT id, conversation_id, parent_context_id, context_activation_time, created_at, current_leaf_message_id, title FROM contexts
WHERE conversation_id = $1
ORDER BY context_activation_time DESC
LIMIT 1
`

func (q *Queries) GetActiveContextByConversation(ctx context.Context, conversationID uuid.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, getActiveContextByConversation, conversationID)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ParentContextID,
		&i.ContextActivationTime,
		&i.CreatedAt,
		&i.CurrentLeafMessageID,
		&i.Title,
	)
	return i, err
}

const getContextByID = `-- name: GetContextByID :one
SELECT id, conversation_id, parent_context_id, context_activation_time, created_at, current_leaf_message_id, title FROM contexts WHERE id = $1
`

func (q *Queries) GetContextByID(ctx context.Context, id uuid.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, getContextByID, id)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ParentContextID,
		&i.ContextActivationTime,
		&i.CreatedAt,
		&i.CurrentLeafMessageID,
		&i.Title,
	)
	return i, err
}

const getContextByIDForUpdate = `-- name: GetContextByIDForUpdate :one
SELECT id, conversation_id, parent_context_id, context_activation_time, created_at, current_leaf_message_id, title FROM contexts WHERE id = $1 FOR UPDATE
`

// Row-locks the context for the duration of the enclosing transaction.
// Used by SendMessage to serialize the
//
//	resolve-parent → insert-user-message → advance-cursor
//
// critical section across concurrent sends on the same context, so the
// second SendMessage observes the first's committed state and produces
// siblings (not a chain) when neither specifies an explicit parent.
func (q *Queries) GetContextByIDForUpdate(ctx context.Context, id uuid.UUID) (Context, error) {
	row := q.db.QueryRow(ctx, getContextByIDForUpdate, id)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ParentContextID,
		&i.ContextActivationTime,
		&i.CreatedAt,
		&i.CurrentLeafMessageID,
		&i.Title,
	)
	return i, err
}

const listContextsByConversation = `-- name: ListContextsByConversation :many
SELECT
    c.id, c.conversation_id, c.parent_context_id, c.context_activation_time, c.created_at, c.current_leaf_message_id, c.title,
    COUNT(m.id)::BIGINT AS message_count
FROM contexts c
LEFT JOIN messages m ON m.context_id = c.id
WHERE c.conversation_id = $1
GROUP BY c.id
ORDER BY c.context_activation_time DESC
`

type ListContextsByConversationRow struct {
	ID                    uuid.UUID
	ConversationID        uuid.UUID
	ParentContextID       *uuid.UUID
	ContextActivationTime time.Time
	CreatedAt             time.Time
	CurrentLeafMessageID  *uuid.UUID
	Title                 *string
	MessageCount          int64
}

// Per-context message_count is aggregated in a single query so the client
// can render the context list without N+1 round trips.
func (q *Queries) ListContextsByConversation(ctx context.Context, conversationID uuid.UUID) ([]ListContextsByConversationRow, error) {
	rows, err := q.db.Query(ctx, listContextsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContextsByConversationRow
	for rows.Next() {
		var i ListContextsByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ParentContextID,
			&i.ContextActivationTime,
			&i.CreatedAt,
			&i.CurrentLeafMessageID,
			&i.Title,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContextActivationTime = `-- name: UpdateContextActivationTime :one
UPDATE contexts
SET context_activation_time = $2
WHERE id = $1
RETURNING id, conversation_id, parent_context_id, context_activation_time, created_at, current_leaf_message_id, title
`

type UpdateContextActivationTimeParams struct {
	ID                    uuid.UUID
	ContextActivationTime time.Time
}

func (q *Queries) UpdateContextActivationTime(ctx context.Context, arg UpdateContextActivationTimeParams) (Context, error) {
	row := q.db.QueryRow(ctx, updateContextActivationTime, arg.ID, arg.ContextActivationTime)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ParentContextID,
		&i.ContextActivationTime,
		&i.CreatedAt,
		&i.CurrentLeafMessageID,
		&i.Title,
	)
	return i, err
}

const updateContextCurrentLeaf = `-- name: UpdateContextCurrentLeaf :one
UPDATE contexts
SET current_leaf_message_id = $2
WHERE id = $1
RETURNING id, conversation_id, parent_context_id, context_activation_time, created_at, current_leaf_message_id, title
`

type UpdateContextCurrentLeafParams struct {
	ID                   uuid.UUID
	CurrentLeafMessageID *uuid.UUID
}

// Sets the per-context cursor for "the tip the user is currently viewing."
// Pass NULL for current_leaf_message_id to clear the cursor.
func (q *Queries) UpdateContextCurrentLeaf(ctx context.Context, arg UpdateContextCurrentLeafParams) (Context, error) {
	row := q.db.QueryRow(ctx, updateContextCurrentLeaf, arg.ID, arg.CurrentLeafMessageID)
	var i Context
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ParentContextID,
		&i.ContextActivationTime,
		&i.CreatedAt,
		&i.CurrentLeafMessageID,
		&i.Title,
	)
	return i, err
}

const updateContextTitle = `-- name: UpdateContextTitle :exec
UPDATE contexts SET title = $2 WHERE id = $1
`

type UpdateContextTitleParams struct {
	ID    uuid.UUID
	Title *string
}

// Sets the human-friendly title for a Context. Pass NULL to clear.
// Populated automatically after the first assistant turn lands in the
// context (when profile title settings are configured); editable by user.
func (q *Queries) UpdateContextTitle(ctx context.Context, arg UpdateContextTitleParams) error {
	_, err := q.db.Exec(ctx, updateContextTitle, arg.ID, arg.Title)
	return err
}
