// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    id, user_id, profile_id, title, settings
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, profile_id, title, settings, created_at, updated_at
`

type CreateConversationParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ProfileID uuid.UUID
	Title     *string
	Settings  []byte
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.UserID,
		arg.ProfileID,
		arg.Title,
		arg.Settings,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileID,
		&i.Title,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, user_id, profile_id, title, settings, created_at, updated_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileID,
		&i.Title,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationsByUser = `-- name: ListConversationsByUser :many
SELECT id, user_id, profile_id, title, settings, created_at, updated_at FROM conversations
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConversationsByUser(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProfileID,
			&i.Title,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConversationSettings = `-- name: UpdateConversationSettings :exec
UPDATE conversations SET settings = $2, updated_at = NOW() WHERE id = $1
`

type UpdateConversationSettingsParams struct {
	ID       uuid.UUID
	Settings []byte
}

func (q *Queries) UpdateConversationSettings(ctx context.Context, arg UpdateConversationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateConversationSettings, arg.ID, arg.Settings)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE conversations SET title = $2, updated_at = NOW() WHERE id = $1
`

type UpdateConversationTitleParams struct {
	ID    uuid.UUID
	Title *string
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.Exec(ctx, updateConversationTitle, arg.ID, arg.Title)
	return err
}
