// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (
    id, user_id, profile_id, title, settings
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, profile_id, title, settings, created_at, updated_at, archived_at, pinned_at
`

type CreateConversationParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	ProfileID uuid.UUID
	Title     *string
	Settings  []byte
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.UserID,
		arg.ProfileID,
		arg.Title,
		arg.Settings,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileID,
		&i.Title,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.PinnedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = $1
`

func (q *Queries) DeleteConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConversation, id)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, user_id, profile_id, title, settings, created_at, updated_at, archived_at, pinned_at FROM conversations WHERE id = $1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileID,
		&i.Title,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
		&i.PinnedAt,
	)
	return i, err
}

const listConversationsByUser = `-- name: ListConversationsByUser :many
SELECT id, user_id, profile_id, title, settings, created_at, updated_at, archived_at, pinned_at FROM conversations
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListConversationsByUser(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProfileID,
			&i.Title,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.PinnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByUserRecentlyCreated = `-- name: ListConversationsByUserRecentlyCreated :many
SELECT
    c.id, c.user_id, c.profile_id, c.title, c.settings, c.created_at, c.updated_at, c.archived_at, c.pinned_at,
    COALESCE(
        (SELECT MAX(m.created_at) FROM messages m
         JOIN contexts ctx ON ctx.id = m.context_id
         WHERE ctx.conversation_id = c.id),
        c.created_at
    ) AS last_activity_at
FROM conversations c
WHERE c.user_id = $1
  AND (c.archived_at IS NOT NULL) = $2::bool
  AND c.pinned_at IS NULL
  AND ($3::text IS NULL
       OR (c.title IS NOT NULL
           AND c.title ILIKE '%' || $3::text || '%'))
  AND ($4::uuid IS NULL
       OR c.profile_id = $4::uuid)
  AND ($5::timestamptz IS NULL
       OR (c.created_at, c.id) < ($5::timestamptz, $6::uuid))
ORDER BY c.created_at DESC, c.id DESC
LIMIT $7
`

type ListConversationsByUserRecentlyCreatedParams struct {
	UserID     uuid.UUID
	Archived   bool
	TitleQuery *string
	ProfileID  *uuid.UUID
	CursorKey  *time.Time
	CursorID   *uuid.UUID
	PageLimit  int32
}

type ListConversationsByUserRecentlyCreatedRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ProfileID      uuid.UUID
	Title          *string
	Settings       []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ArchivedAt     *time.Time
	PinnedAt       *time.Time
	LastActivityAt time.Time
}

// Same filters as ListConversationsByUserRecentlyUsed but ordered by the
// conversation's own created_at — the freshest creation always wins
// regardless of subsequent message traffic. Still computes
// last_activity_at for clients that want to display "last used" alongside
// the row even when sorting by creation. Same keyset scheme, keyed on
// created_at.
func (q *Queries) ListConversationsByUserRecentlyCreated(ctx context.Context, arg ListConversationsByUserRecentlyCreatedParams) ([]ListConversationsByUserRecentlyCreatedRow, error) {
	rows, err := q.db.Query(ctx, listConversationsByUserRecentlyCreated,
		arg.UserID,
		arg.Archived,
		arg.TitleQuery,
		arg.ProfileID,
		arg.CursorKey,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsByUserRecentlyCreatedRow
	for rows.Next() {
		var i ListConversationsByUserRecentlyCreatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProfileID,
			&i.Title,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.PinnedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByUserRecentlyUsed = `-- name: ListConversationsByUserRecentlyUsed :many
WITH convs AS (
    SELECT
        c.id, c.user_id, c.profile_id, c.title, c.settings, c.created_at, c.updated_at, c.archived_at, c.pinned_at,
        COALESCE(
            (SELECT MAX(m.created_at) FROM messages m
             JOIN contexts ctx ON ctx.id = m.context_id
             WHERE ctx.conversation_id = c.id),
            c.created_at
        ) AS last_activity_at
    FROM conversations c
    WHERE c.user_id = $1
      AND (c.archived_at IS NOT NULL) = $5::bool
      AND c.pinned_at IS NULL
      AND ($6::text IS NULL
           OR (c.title IS NOT NULL
               AND c.title ILIKE '%' || $6::text || '%'))
      AND ($7::uuid IS NULL
           OR c.profile_id = $7::uuid)
)
SELECT id, user_id, profile_id, title, settings, created_at, updated_at, archived_at, pinned_at, last_activity_at FROM convs
WHERE ($2::timestamptz IS NULL
       OR (last_activity_at, id) < ($2::timestamptz, $3::uuid))
ORDER BY last_activity_at DESC, id DESC
LIMIT $4
`

type ListConversationsByUserRecentlyUsedParams struct {
	UserID     uuid.UUID
	CursorKey  *time.Time
	CursorID   *uuid.UUID
	PageLimit  int32
	Archived   bool
	TitleQuery *string
	ProfileID  *uuid.UUID
}

type ListConversationsByUserRecentlyUsedRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ProfileID      uuid.UUID
	Title          *string
	Settings       []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ArchivedAt     *time.Time
	PinnedAt       *time.Time
	LastActivityAt time.Time
}

// Returns conversations sorted by the most recent message activity, with
// created_at as the fallback for conversations that haven't received a
// message yet. Optional filters: case-insensitive title substring (NULL
// skips the filter; conversations with no title are excluded when set);
// profile_id (NULL skips the filter).
//
// Keyset paging: cursor_key/cursor_id (NULL = first page) resume after
// the row with that (last_activity_at, id) tuple; id breaks timestamp
// ties so a page boundary through same-instant rows can't skip or
// duplicate. page_limit callers pass limit+1 to detect a next page.
func (q *Queries) ListConversationsByUserRecentlyUsed(ctx context.Context, arg ListConversationsByUserRecentlyUsedParams) ([]ListConversationsByUserRecentlyUsedRow, error) {
	rows, err := q.db.Query(ctx, listConversationsByUserRecentlyUsed,
		arg.UserID,
		arg.CursorKey,
		arg.CursorID,
		arg.PageLimit,
		arg.Archived,
		arg.TitleQuery,
		arg.ProfileID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsByUserRecentlyUsedRow
	for rows.Next() {
		var i ListConversationsByUserRecentlyUsedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProfileID,
			&i.Title,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.PinnedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedConversationsByUser = `-- name: ListPinnedConversationsByUser :many
SELECT
    c.id, c.user_id, c.profile_id, c.title, c.settings, c.created_at, c.updated_at, c.archived_at, c.pinned_at,
    COALESCE(
        (SELECT MAX(m.created_at) FROM messages m
         JOIN contexts ctx ON ctx.id = m.context_id
         WHERE ctx.conversation_id = c.id),
        c.created_at
    ) AS last_activity_at
FROM conversations c
WHERE c.user_id = $1
  AND c.pinned_at IS NOT NULL
  AND c.archived_at IS NULL
  AND ($2::text IS NULL
       OR (c.title IS NOT NULL
           AND c.title ILIKE '%' || $2::text || '%'))
  AND ($3::uuid IS NULL
       OR c.profile_id = $3::uuid)
ORDER BY c.pinned_at DESC, c.id DESC
LIMIT 100
`

type ListPinnedConversationsByUserParams struct {
	UserID     uuid.UUID
	TitleQuery *string
	ProfileID  *uuid.UUID
}

type ListPinnedConversationsByUserRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ProfileID      uuid.UUID
	Title          *string
	Settings       []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ArchivedAt     *time.Time
	PinnedAt       *time.Time
	LastActivityAt time.Time
}

// The pinned block served ahead of page one. Same filters as the paged
// queries; never paged itself (pins are few; LIMIT 100 is a guardrail,
// matching MaxListPageSize). Every pinned row is active by invariant,
// but the archived filter keeps the archived listing honest anyway.
func (q *Queries) ListPinnedConversationsByUser(ctx context.Context, arg ListPinnedConversationsByUserParams) ([]ListPinnedConversationsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPinnedConversationsByUser, arg.UserID, arg.TitleQuery, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinnedConversationsByUserRow
	for rows.Next() {
		var i ListPinnedConversationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProfileID,
			&i.Title,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.PinnedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationArchived = `-- name: SetConversationArchived :exec
UPDATE conversations
SET archived_at = CASE WHEN $2::bool THEN NOW() ELSE NULL END,
    pinned_at   = CASE WHEN $2::bool THEN NULL ELSE pinned_at END,
    updated_at = NOW()
WHERE id = $1
`

type SetConversationArchivedParams struct {
	ID       uuid.UUID
	Archived bool
}

// Archive (TRUE → archived_at = now()) or unarchive (FALSE → NULL).
// Archiving also clears the pin: pinned is an active-list concept, and
// keeping them exclusive means every pinned row is an active row (the
// list queries rely on that invariant).
func (q *Queries) SetConversationArchived(ctx context.Context, arg SetConversationArchivedParams) error {
	_, err := q.db.Exec(ctx, setConversationArchived, arg.ID, arg.Archived)
	return err
}

const setConversationPinned = `-- name: SetConversationPinned :exec
UPDATE conversations
SET pinned_at = CASE WHEN $2::bool THEN NOW() ELSE NULL END,
    updated_at = NOW()
WHERE id = $1
`

type SetConversationPinnedParams struct {
	ID     uuid.UUID
	Pinned bool
}

func (q *Queries) SetConversationPinned(ctx context.Context, arg SetConversationPinnedParams) error {
	_, err := q.db.Exec(ctx, setConversationPinned, arg.ID, arg.Pinned)
	return err
}

const touchConversationUpdatedAt = `-- name: TouchConversationUpdatedAt :exec
UPDATE conversations SET updated_at = NOW() WHERE id = $1
`

// Bump the coarse mutation stamp without changing any field. Message
// edits and deletes call this so clients' cheap staleness check
// (compare updated_at + active context + leaf) can detect content
// mutations that move neither the leaf nor any conversation column.
func (q *Queries) TouchConversationUpdatedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchConversationUpdatedAt, id)
	return err
}

const updateConversationSettings = `-- name: UpdateConversationSettings :exec
UPDATE conversations SET settings = $2, updated_at = NOW() WHERE id = $1
`

type UpdateConversationSettingsParams struct {
	ID       uuid.UUID
	Settings []byte
}

func (q *Queries) UpdateConversationSettings(ctx context.Context, arg UpdateConversationSettingsParams) error {
	_, err := q.db.Exec(ctx, updateConversationSettings, arg.ID, arg.Settings)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE conversations SET title = $2, updated_at = NOW() WHERE id = $1
`

type UpdateConversationTitleParams struct {
	ID    uuid.UUID
	Title *string
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.Exec(ctx, updateConversationTitle, arg.ID, arg.Title)
	return err
}
