// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cost_events.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertCostEvent = `-- name: InsertCostEvent :exec
INSERT INTO cost_events (
    provider_id, model_id, amount_usd, message_id
) VALUES (
    $1, $2, $3, $4
)
`

type InsertCostEventParams struct {
	ProviderID uuid.UUID
	ModelID    string
	AmountUsd  pgtype.Numeric
	MessageID  *uuid.UUID
}

// Records one cost-incurring event. Called from the stream supervisor on
// assistant + compression_summary materialisation when total_cost_usd is
// non-null and > 0. Errored runs still log if the provider charged
// tokens — the user paid even if the response was junk.
func (q *Queries) InsertCostEvent(ctx context.Context, arg InsertCostEventParams) error {
	_, err := q.db.Exec(ctx, insertCostEvent,
		arg.ProviderID,
		arg.ModelID,
		arg.AmountUsd,
		arg.MessageID,
	)
	return err
}

const listProviderCostTotals = `-- name: ListProviderCostTotals :many
SELECT
    p.id          AS provider_id,
    p.label       AS provider_label,
    p.type        AS provider_type,
    COALESCE(SUM(c.amount_usd), 0)::NUMERIC AS total_cost_usd,
    COUNT(c.id)::BIGINT                     AS event_count
FROM user_model_providers p
LEFT JOIN cost_events c
    ON c.provider_id = p.id
   AND c.occurred_at >= COALESCE($2::timestamptz, '-infinity'::timestamptz)
   AND c.occurred_at <  COALESCE($3::timestamptz, 'infinity'::timestamptz)
WHERE p.user_id = $1
GROUP BY p.id, p.label, p.type
ORDER BY p.label
`

type ListProviderCostTotalsParams struct {
	UserID uuid.UUID
	Since  *time.Time
	Until  *time.Time
}

type ListProviderCostTotalsRow struct {
	ProviderID    uuid.UUID
	ProviderLabel string
	ProviderType  string
	TotalCostUsd  pgtype.Numeric
	EventCount    int64
}

// Per-provider running totals across the ledger, optionally bounded by
// a [since, until) occurred_at window. Drives the iOS Settings → Cost
// screen — one row per configured provider, single dollar amount per
// row. Sorted alphabetically by the provider's label so the list reads
// stably across reloads. Providers with no events in the window are
// still surfaced (LEFT JOIN with the window predicate in the JOIN ON,
// not the WHERE — putting it in WHERE would silently drop them).
func (q *Queries) ListProviderCostTotals(ctx context.Context, arg ListProviderCostTotalsParams) ([]ListProviderCostTotalsRow, error) {
	rows, err := q.db.Query(ctx, listProviderCostTotals, arg.UserID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProviderCostTotalsRow
	for rows.Next() {
		var i ListProviderCostTotalsRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.ProviderLabel,
			&i.ProviderType,
			&i.TotalCostUsd,
			&i.EventCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
