// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    id, user_id, sha256, mime_type, size_bytes, original_filename
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, sha256) DO UPDATE
    SET sha256 = EXCLUDED.sha256
RETURNING id, user_id, sha256, mime_type, size_bytes, original_filename, created_at
`

type CreateFileParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Sha256           string
	MimeType         string
	SizeBytes        int64
	OriginalFilename *string
}

// Idempotent on (user_id, sha256) — re-uploading the same content by
// the same user returns the existing row instead of inserting a
// duplicate. The DO UPDATE no-op pattern is the standard way to make
// ON CONFLICT path RETURN the existing row (a plain DO NOTHING would
// return no rows).
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.UserID,
		arg.Sha256,
		arg.MimeType,
		arg.SizeBytes,
		arg.OriginalFilename,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sha256,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1
`

// Caller's responsibility to ensure no message_attachments still reference
// the file (or accept the ON DELETE CASCADE on message_attachments).
func (q *Queries) DeleteFile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, user_id, sha256, mime_type, size_bytes, original_filename, created_at FROM files
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFile(ctx context.Context, id uuid.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sha256,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByUserAndSHA = `-- name: GetFileByUserAndSHA :one
SELECT id, user_id, sha256, mime_type, size_bytes, original_filename, created_at FROM files
WHERE user_id = $1 AND sha256 = $2
LIMIT 1
`

type GetFileByUserAndSHAParams struct {
	UserID uuid.UUID
	Sha256 string
}

func (q *Queries) GetFileByUserAndSHA(ctx context.Context, arg GetFileByUserAndSHAParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByUserAndSHA, arg.UserID, arg.Sha256)
	var i File
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sha256,
		&i.MimeType,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.CreatedAt,
	)
	return i, err
}

const listFilesForUser = `-- name: ListFilesForUser :many
SELECT id, user_id, sha256, mime_type, size_bytes, original_filename, created_at FROM files
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListFilesForUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListFilesForUser(ctx context.Context, arg ListFilesForUserParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Sha256,
			&i.MimeType,
			&i.SizeBytes,
			&i.OriginalFilename,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
