// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gemini_caches.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteGeminiCache = `-- name: DeleteGeminiCache :exec
DELETE FROM gemini_caches WHERE context_id = $1 AND model_id = $2
`

type DeleteGeminiCacheParams struct {
	ContextID uuid.UUID
	ModelID   string
}

func (q *Queries) DeleteGeminiCache(ctx context.Context, arg DeleteGeminiCacheParams) error {
	_, err := q.db.Exec(ctx, deleteGeminiCache, arg.ContextID, arg.ModelID)
	return err
}

const getGeminiCache = `-- name: GetGeminiCache :one
SELECT context_id, model_id, cache_name, prefix_message_count, prefix_hash, created_at, expires_at FROM gemini_caches
WHERE context_id = $1 AND model_id = $2
`

type GetGeminiCacheParams struct {
	ContextID uuid.UUID
	ModelID   string
}

func (q *Queries) GetGeminiCache(ctx context.Context, arg GetGeminiCacheParams) (GeminiCach, error) {
	row := q.db.QueryRow(ctx, getGeminiCache, arg.ContextID, arg.ModelID)
	var i GeminiCach
	err := row.Scan(
		&i.ContextID,
		&i.ModelID,
		&i.CacheName,
		&i.PrefixMessageCount,
		&i.PrefixHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const upsertGeminiCache = `-- name: UpsertGeminiCache :exec
INSERT INTO gemini_caches (
    context_id, model_id, cache_name, prefix_message_count, prefix_hash, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (context_id, model_id) DO UPDATE SET
    cache_name           = EXCLUDED.cache_name,
    prefix_message_count = EXCLUDED.prefix_message_count,
    prefix_hash          = EXCLUDED.prefix_hash,
    created_at           = now(),
    expires_at           = EXCLUDED.expires_at
`

type UpsertGeminiCacheParams struct {
	ContextID          uuid.UUID
	ModelID            string
	CacheName          string
	PrefixMessageCount int32
	PrefixHash         string
	ExpiresAt          time.Time
}

func (q *Queries) UpsertGeminiCache(ctx context.Context, arg UpsertGeminiCacheParams) error {
	_, err := q.db.Exec(ctx, upsertGeminiCache,
		arg.ContextID,
		arg.ModelID,
		arg.CacheName,
		arg.PrefixMessageCount,
		arg.PrefixHash,
		arg.ExpiresAt,
	)
	return err
}
