// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssistantMessageWithUsage = `-- name: CreateAssistantMessageWithUsage :one
INSERT INTO messages (
    id, context_id, parent_id, role, content,
    raw_content, thinking, thinking_provider_type, thinking_rendered_text,
    thinking_duration_ms,
    provider_id, model_id,
    input_tokens, output_tokens, cache_read_tokens, cache_write_tokens,
    reasoning_tokens, provider_usage_raw,
    input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd,
    tool_cost_usd, total_cost_usd,
    error_payload,
    explicit_cache_attached,
    tool_calls,
    finish_reason
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10,
    $11, $12,
    $13, $14, $15, $16,
    $17, $18,
    $19, $20, $21, $22,
    $23, $24,
    $25,
    $26,
    $27,
    $28
)
RETURNING id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd
`

type CreateAssistantMessageWithUsageParams struct {
	ID                    uuid.UUID
	ContextID             uuid.UUID
	ParentID              *uuid.UUID
	Role                  string
	Content               string
	RawContent            *string
	Thinking              []byte
	ThinkingProviderType  *string
	ThinkingRenderedText  *string
	ThinkingDurationMs    *int32
	ProviderID            *uuid.UUID
	ModelID               *string
	InputTokens           *int32
	OutputTokens          *int32
	CacheReadTokens       *int32
	CacheWriteTokens      *int32
	ReasoningTokens       *int32
	ProviderUsageRaw      []byte
	InputCostUsd          pgtype.Numeric
	OutputCostUsd         pgtype.Numeric
	CacheReadCostUsd      pgtype.Numeric
	CacheWriteCostUsd     pgtype.Numeric
	ToolCostUsd           pgtype.Numeric
	TotalCostUsd          pgtype.Numeric
	ErrorPayload          []byte
	ExplicitCacheAttached *bool
	ToolCalls             []byte
	FinishReason          *string
}

// Used by the stream supervisor at materialization. Allows the assistant turn
// (or the compression_summary record) to be inserted with usage + cost
// columns populated atomically. error_payload is set when the stream
// terminated in an errored/cancelled state — captures the failure inline so
// the UI can render the message as a first-class errored history entry.
// thinking_duration_ms records the elapsed time (ms) between the first and
// last thinking_delta chunk seen on the run; NULL when the assistant didn't
// reason at all.
func (q *Queries) CreateAssistantMessageWithUsage(ctx context.Context, arg CreateAssistantMessageWithUsageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createAssistantMessageWithUsage,
		arg.ID,
		arg.ContextID,
		arg.ParentID,
		arg.Role,
		arg.Content,
		arg.RawContent,
		arg.Thinking,
		arg.ThinkingProviderType,
		arg.ThinkingRenderedText,
		arg.ThinkingDurationMs,
		arg.ProviderID,
		arg.ModelID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.ReasoningTokens,
		arg.ProviderUsageRaw,
		arg.InputCostUsd,
		arg.OutputCostUsd,
		arg.CacheReadCostUsd,
		arg.CacheWriteCostUsd,
		arg.ToolCostUsd,
		arg.TotalCostUsd,
		arg.ErrorPayload,
		arg.ExplicitCacheAttached,
		arg.ToolCalls,
		arg.FinishReason,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, context_id, parent_id, role, content,
    raw_content, thinking, thinking_provider_type, thinking_rendered_text,
    provider_id, model_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11
)
RETURNING id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd
`

type CreateMessageParams struct {
	ID                   uuid.UUID
	ContextID            uuid.UUID
	ParentID             *uuid.UUID
	Role                 string
	Content              string
	RawContent           *string
	Thinking             []byte
	ThinkingProviderType *string
	ThinkingRenderedText *string
	ProviderID           *uuid.UUID
	ModelID              *string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ContextID,
		arg.ParentID,
		arg.Role,
		arg.Content,
		arg.RawContent,
		arg.Thinking,
		arg.ThinkingProviderType,
		arg.ThinkingRenderedText,
		arg.ProviderID,
		arg.ModelID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
	)
	return i, err
}

const deleteMessageByID = `-- name: DeleteMessageByID :exec
DELETE FROM messages WHERE id = $1
`

// The cascade=true path. With ON DELETE CASCADE on parent_id (migration 00006),
// this single DELETE removes the descendant subtree too.
func (q *Queries) DeleteMessageByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageByID, id)
	return err
}

const getCompressionSummaryInContext = `-- name: GetCompressionSummaryInContext :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd FROM messages
WHERE context_id = $1 AND role = 'compression_summary'
ORDER BY created_at DESC
LIMIT 1
`

// Returns the (single) compression_summary message in a context, if any. Used
// by PromoteCompactionToNewContext to read the (possibly user-edited) content
// and seed the new context's role=context message.
func (q *Queries) GetCompressionSummaryInContext(ctx context.Context, contextID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getCompressionSummaryInContext, contextID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
	)
	return i, err
}

const getContextLeafMessage = `-- name: GetContextLeafMessage :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd FROM messages m
WHERE m.context_id = $1
  AND m.id NOT IN (
    SELECT DISTINCT c.parent_id FROM messages c
    WHERE c.context_id = $1 AND c.parent_id IS NOT NULL
  )
ORDER BY m.id DESC
LIMIT 1
`

// Returns the leaf of a context's message tree: the message that no other
// message in the same context references as a parent. When the context has
// multiple dangling branches (shouldn't happen in normal use), returns the
// one with the greatest id (most recently created per UUIDv7 monotonicity).
// Returns no rows when the context is truly empty.
func (q *Queries) GetContextLeafMessage(ctx context.Context, contextID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getContextLeafMessage, contextID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
	)
	return i, err
}

const getContextRoleMessageInContext = `-- name: GetContextRoleMessageInContext :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd FROM messages
WHERE context_id = $1 AND role = 'context'
ORDER BY created_at
LIMIT 1
`

// Returns the (single) role=context message in a Context. Each Context has at
// most one such message; APPEND-mode compression reads it to chain forward.
func (q *Queries) GetContextRoleMessageInContext(ctx context.Context, contextID uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getContextRoleMessageInContext, contextID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
	)
	return i, err
}

const hasCompressionSummaryInContext = `-- name: HasCompressionSummaryInContext :one
SELECT EXISTS(
    SELECT 1 FROM messages
    WHERE context_id = $1
      AND role = 'compression_summary'
      AND error_payload IS NULL
)::BOOLEAN AS has_summary
`

// True iff the context contains at least one role=compression_summary row that
// did NOT fail (error_payload IS NULL). SendMessage / Compact use this as a
// precondition: a clean pending summary must be promoted
// (PromoteCompactionToNewContext) or deleted (DeleteMessage) before more turns
// can land. Errored compression_summary rows are first-class history entries
// the user can review; they do not gate the conversation — the user retries
// by either deleting the failed summary or kicking off a fresh compaction.
func (q *Queries) HasCompressionSummaryInContext(ctx context.Context, contextID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasCompressionSummaryInContext, contextID)
	var has_summary bool
	err := row.Scan(&has_summary)
	return has_summary, err
}

const listMessageAncestorChain = `-- name: ListMessageAncestorChain :many
WITH RECURSIVE chain AS (
    SELECT messages.id, messages.context_id, messages.parent_id, messages.role, messages.content, messages.raw_content, messages.thinking, messages.thinking_provider_type, messages.thinking_rendered_text, messages.provider_id, messages.model_id, messages.created_at, messages.input_tokens, messages.output_tokens, messages.cache_read_tokens, messages.cache_write_tokens, messages.reasoning_tokens, messages.provider_usage_raw, messages.input_cost_usd, messages.output_cost_usd, messages.cache_read_cost_usd, messages.cache_write_cost_usd, messages.total_cost_usd, messages.edited_at, messages.error_payload, messages.thinking_duration_ms, messages.explicit_cache_attached, messages.tool_calls, messages.finish_reason, messages.tool_cost_usd, 0 AS depth
    FROM messages
    WHERE messages.id = $1
    UNION ALL
    SELECT m.id, m.context_id, m.parent_id, m.role, m.content, m.raw_content, m.thinking, m.thinking_provider_type, m.thinking_rendered_text, m.provider_id, m.model_id, m.created_at, m.input_tokens, m.output_tokens, m.cache_read_tokens, m.cache_write_tokens, m.reasoning_tokens, m.provider_usage_raw, m.input_cost_usd, m.output_cost_usd, m.cache_read_cost_usd, m.cache_write_cost_usd, m.total_cost_usd, m.edited_at, m.error_payload, m.thinking_duration_ms, m.explicit_cache_attached, m.tool_calls, m.finish_reason, m.tool_cost_usd, c.depth + 1
    FROM messages m
    INNER JOIN chain c ON m.id = c.parent_id
)
SELECT chain.id, chain.context_id, chain.parent_id, chain.role, chain.content,
       chain.raw_content, chain.thinking, chain.thinking_provider_type, chain.thinking_rendered_text,
       chain.thinking_duration_ms,
       chain.provider_id, chain.model_id,
       chain.input_tokens, chain.output_tokens, chain.cache_read_tokens, chain.cache_write_tokens,
       chain.reasoning_tokens, chain.provider_usage_raw,
       chain.input_cost_usd, chain.output_cost_usd, chain.cache_read_cost_usd, chain.cache_write_cost_usd,
       chain.tool_cost_usd,
       chain.total_cost_usd,
       chain.error_payload,
       chain.tool_calls,
       chain.finish_reason,
       chain.created_at,
       chain.edited_at,
       (
           SELECT COUNT(*)::INT FROM messages m
           WHERE m.id <> chain.id
             AND (
                 (chain.parent_id IS NOT NULL AND m.parent_id = chain.parent_id)
                 OR (chain.parent_id IS NULL AND m.context_id = chain.context_id AND m.parent_id IS NULL)
             )
       )::INT AS sibling_count
FROM chain
ORDER BY depth DESC
`

type ListMessageAncestorChainRow struct {
	ID                   uuid.UUID
	ContextID            uuid.UUID
	ParentID             *uuid.UUID
	Role                 string
	Content              string
	RawContent           *string
	Thinking             []byte
	ThinkingProviderType *string
	ThinkingRenderedText *string
	ThinkingDurationMs   *int32
	ProviderID           *uuid.UUID
	ModelID              *string
	InputTokens          *int32
	OutputTokens         *int32
	CacheReadTokens      *int32
	CacheWriteTokens     *int32
	ReasoningTokens      *int32
	ProviderUsageRaw     []byte
	InputCostUsd         pgtype.Numeric
	OutputCostUsd        pgtype.Numeric
	CacheReadCostUsd     pgtype.Numeric
	CacheWriteCostUsd    pgtype.Numeric
	ToolCostUsd          pgtype.Numeric
	TotalCostUsd         pgtype.Numeric
	ErrorPayload         []byte
	ToolCalls            []byte
	FinishReason         *string
	CreatedAt            time.Time
	EditedAt             *time.Time
	SiblingCount         int32
}

// Walks parent_id from the leaf back to the root, returning rows root-first.
// sibling_count: number of OTHER messages sharing this row's parent — i.e.
// branches forking off the same parent. The UI uses it to render fork
// indicators alongside the linear chain.
func (q *Queries) ListMessageAncestorChain(ctx context.Context, id uuid.UUID) ([]ListMessageAncestorChainRow, error) {
	rows, err := q.db.Query(ctx, listMessageAncestorChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessageAncestorChainRow
	for rows.Next() {
		var i ListMessageAncestorChainRow
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.ParentID,
			&i.Role,
			&i.Content,
			&i.RawContent,
			&i.Thinking,
			&i.ThinkingProviderType,
			&i.ThinkingRenderedText,
			&i.ThinkingDurationMs,
			&i.ProviderID,
			&i.ModelID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.ReasoningTokens,
			&i.ProviderUsageRaw,
			&i.InputCostUsd,
			&i.OutputCostUsd,
			&i.CacheReadCostUsd,
			&i.CacheWriteCostUsd,
			&i.ToolCostUsd,
			&i.TotalCostUsd,
			&i.ErrorPayload,
			&i.ToolCalls,
			&i.FinishReason,
			&i.CreatedAt,
			&i.EditedAt,
			&i.SiblingCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByContext = `-- name: ListMessagesByContext :many
SELECT id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd FROM messages
WHERE context_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListMessagesByContext(ctx context.Context, contextID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByContext, contextID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ContextID,
			&i.ParentID,
			&i.Role,
			&i.Content,
			&i.RawContent,
			&i.Thinking,
			&i.ThinkingProviderType,
			&i.ThinkingRenderedText,
			&i.ProviderID,
			&i.ModelID,
			&i.CreatedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.ReasoningTokens,
			&i.ProviderUsageRaw,
			&i.InputCostUsd,
			&i.OutputCostUsd,
			&i.CacheReadCostUsd,
			&i.CacheWriteCostUsd,
			&i.TotalCostUsd,
			&i.EditedAt,
			&i.ErrorPayload,
			&i.ThinkingDurationMs,
			&i.ExplicitCacheAttached,
			&i.ToolCalls,
			&i.FinishReason,
			&i.ToolCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reparentChildren = `-- name: ReparentChildren :exec
UPDATE messages
SET parent_id = $2
WHERE parent_id = $1
`

type ReparentChildrenParams struct {
	ParentID   *uuid.UUID
	ParentID_2 *uuid.UUID
}

// Promotes every direct child of $1 to point at $2 (which may be NULL — that
// makes them roots in the context). Used by DeleteMessage(cascade=false) just
// before the DELETE, so the FK's ON DELETE CASCADE has nothing to find.
func (q *Queries) ReparentChildren(ctx context.Context, arg ReparentChildrenParams) error {
	_, err := q.db.Exec(ctx, reparentChildren, arg.ParentID, arg.ParentID_2)
	return err
}

const updateMessageContentRole = `-- name: UpdateMessageContentRole :one
UPDATE messages
SET content   = $2,
    role      = COALESCE($3, role),
    edited_at = NOW()
WHERE id = $1
RETURNING id, context_id, parent_id, role, content, raw_content, thinking, thinking_provider_type, thinking_rendered_text, provider_id, model_id, created_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, reasoning_tokens, provider_usage_raw, input_cost_usd, output_cost_usd, cache_read_cost_usd, cache_write_cost_usd, total_cost_usd, edited_at, error_payload, thinking_duration_ms, explicit_cache_attached, tool_calls, finish_reason, tool_cost_usd
`

type UpdateMessageContentRoleParams struct {
	ID      uuid.UUID
	Content string
	Role    *string
}

// In-place edit. content is always set; role is COALESCE'd so the caller can
// pass NULL to leave it unchanged. edited_at = NOW() unconditionally.
// sqlc.narg lets the role param be nullable (sqlc otherwise infers
// non-nullable from the column type).
func (q *Queries) UpdateMessageContentRole(ctx context.Context, arg UpdateMessageContentRoleParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageContentRole, arg.ID, arg.Content, arg.Role)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ContextID,
		&i.ParentID,
		&i.Role,
		&i.Content,
		&i.RawContent,
		&i.Thinking,
		&i.ThinkingProviderType,
		&i.ThinkingRenderedText,
		&i.ProviderID,
		&i.ModelID,
		&i.CreatedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.ReasoningTokens,
		&i.ProviderUsageRaw,
		&i.InputCostUsd,
		&i.OutputCostUsd,
		&i.CacheReadCostUsd,
		&i.CacheWriteCostUsd,
		&i.TotalCostUsd,
		&i.EditedAt,
		&i.ErrorPayload,
		&i.ThinkingDurationMs,
		&i.ExplicitCacheAttached,
		&i.ToolCalls,
		&i.FinishReason,
		&i.ToolCostUsd,
	)
	return i, err
}
