// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile_plugins.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertProfilePlugin = `-- name: InsertProfilePlugin :one
INSERT INTO profile_plugins (profile_id, ordinal, plugin_name, config_encrypted)
VALUES ($1, $2, $3, $4)
RETURNING profile_id, ordinal, plugin_name, config, created_at, updated_at, config_encrypted
`

type InsertProfilePluginParams struct {
	ProfileID       uuid.UUID
	Ordinal         int32
	PluginName      string
	ConfigEncrypted []byte
}

// $4 is config_encrypted (nullable BYTEA); the legacy plaintext
// config column is left NULL on every new row. The service layer's
// read path decrypts config_encrypted and falls back to the plaintext
// column for legacy rows still carrying their pre-rollover JSONB.
func (q *Queries) InsertProfilePlugin(ctx context.Context, arg InsertProfilePluginParams) (ProfilePlugin, error) {
	row := q.db.QueryRow(ctx, insertProfilePlugin,
		arg.ProfileID,
		arg.Ordinal,
		arg.PluginName,
		arg.ConfigEncrypted,
	)
	var i ProfilePlugin
	err := row.Scan(
		&i.ProfileID,
		&i.Ordinal,
		&i.PluginName,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConfigEncrypted,
	)
	return i, err
}

const listProfilePlugins = `-- name: ListProfilePlugins :many
SELECT profile_id, ordinal, plugin_name, config, created_at, updated_at, config_encrypted FROM profile_plugins
WHERE profile_id = $1
ORDER BY ordinal
`

// Returns the ordered plugin pipeline for one profile (no inheritance walk;
// callers do the walk in code so they can short-circuit on a profile that
// defines its own pipeline).
func (q *Queries) ListProfilePlugins(ctx context.Context, profileID uuid.UUID) ([]ProfilePlugin, error) {
	rows, err := q.db.Query(ctx, listProfilePlugins, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfilePlugin
	for rows.Next() {
		var i ProfilePlugin
		if err := rows.Scan(
			&i.ProfileID,
			&i.Ordinal,
			&i.PluginName,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConfigEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceProfilePlugins = `-- name: ReplaceProfilePlugins :exec
DELETE FROM profile_plugins WHERE profile_id = $1
`

// Atomically swap the pipeline. Caller wraps this in a transaction along with
// the per-row inserts via InsertProfilePlugin (an in-tx loop) — there's no
// batch-insert sqlc emit for an arbitrary slice.
func (q *Queries) ReplaceProfilePlugins(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceProfilePlugins, profileID)
	return err
}
