// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AttachFileToMessage(ctx context.Context, arg AttachFileToMessageParams) (MessageAttachment, error)
	// Half of the set-default transaction. Clear must land before Mark: the
	// partial unique index (user_id WHERE is_default) is checked per row, so
	// a single UPDATE that flips the new default on before the old one off
	// trips the constraint against itself.
	ClearDefaultProfile(ctx context.Context, userID uuid.UUID) error
	// Reset the triple when a model swap orphans the existing vector.
	// Backfill picks the row up via ListUnembeddedMessages on the next
	// pass. CHECK invariant still holds (all three back to NULL).
	ClearMessageEmbedding(ctx context.Context, id uuid.UUID) error
	// Compaction runs in OTHER contexts can point at this context as
	// their result; the FK has no ON DELETE action, so null the pointer
	// before the context row goes.
	ClearStreamRunResultContext(ctx context.Context, resultContextID *uuid.UUID) error
	// Capped at 2: the auto-title hook only distinguishes "exactly one
	// assistant turn exists" from everything else, and it fires on EVERY
	// assistant materialization — a full-context list per turn just to
	// count was the cost.
	CountAssistantMessagesCapped(ctx context.Context, contextID uuid.UUID) (int64, error)
	// For the "X calls in the last 7 days" chip on settings.
	CountDeviceToolCallsByUser(ctx context.Context, arg CountDeviceToolCallsByUserParams) (int32, error)
	// Drives the "X / Y embedded" progress chip in the settings UI.
	// Cheap even on millions of rows because the partial
	// messages_unembedded_created_at index is exactly this predicate.
	// Scoped to a user so the chip means "MY unembedded messages."
	CountUnembeddedMessages(ctx context.Context, userID uuid.UUID) (int32, error)
	CountUsers(ctx context.Context) (int64, error)
	// Used by the stream supervisor at materialization. Allows the assistant turn
	// (or the compression_summary record) to be inserted with usage + cost
	// columns populated atomically. error_payload is set when the stream
	// terminated in an errored/cancelled state — captures the failure inline so
	// the UI can render the message as a first-class errored history entry.
	// thinking_duration_ms records the elapsed time (ms) between the first and
	// last thinking_delta chunk seen on the run; NULL when the assistant didn't
	// reason at all.
	CreateAssistantMessageWithUsage(ctx context.Context, arg CreateAssistantMessageWithUsageParams) (Message, error)
	CreateContext(ctx context.Context, arg CreateContextParams) (Context, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	// Idempotent on (user_id, sha256) — re-uploading the same content by
	// the same user returns the existing row instead of inserting a
	// duplicate. The DO UPDATE no-op pattern is the standard way to make
	// ON CONFLICT path RETURN the existing row (a plain DO NOTHING would
	// return no rows).
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateStreamRun(ctx context.Context, arg CreateStreamRunParams) (StreamRun, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// config_encrypted is the AES-256-GCM-sealed JSONB blob; the legacy
	// `config` column is left NULL. The service layer's Get/List path
	// decrypts config_encrypted when present and falls back to plaintext
	// config for any row that hasn't been touched since the encryption
	// rollout.
	CreateUserModelProvider(ctx context.Context, arg CreateUserModelProviderParams) (UserModelProvider, error)
	// Insert the profile's snapshot welcome message at conversation-create
	// time. Role is hard-coded to 'assistant' (the welcome is a greeting,
	// not a system instruction) and is_welcome is set so clients can
	// gate a fake-stream reveal animation on first open.
	CreateWelcomeMessage(ctx context.Context, arg CreateWelcomeMessageParams) (Message, error)
	// Messages (and their attachments / explicit-cache rows) go via
	// ON DELETE CASCADE. Callers must clear stream_runs references first
	// (their context FKs have no cascade).
	DeleteContext(ctx context.Context, id uuid.UUID) error
	DeleteConversation(ctx context.Context, id uuid.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteExplicitCache(ctx context.Context, arg DeleteExplicitCacheParams) error
	// Caller's responsibility to ensure no message_attachments still reference
	// the file (or accept the ON DELETE CASCADE on message_attachments).
	DeleteFile(ctx context.Context, id uuid.UUID) error
	// The cascade=true path. With ON DELETE CASCADE on parent_id (migration 00006),
	// this single DELETE removes the descendant subtree too.
	DeleteMessageByID(ctx context.Context, id uuid.UUID) error
	DeleteProfile(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, tokenHash string) error
	// Rows whose run happened in this context; stream_chunks cascade.
	DeleteStreamRunsByContext(ctx context.Context, contextID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserEmbedderConfig(ctx context.Context, userID uuid.UUID) error
	// Removes the entire row. Drops both credentials and the enabled
	// toggle in one shot — for users who want to fully sever the
	// integration rather than just disable it.
	DeleteUserLangfuseConfig(ctx context.Context, userID uuid.UUID) error
	DeleteUserMCPServer(ctx context.Context, arg DeleteUserMCPServerParams) (int64, error)
	DeleteUserModel(ctx context.Context, arg DeleteUserModelParams) error
	DeleteUserModelProvider(ctx context.Context, id uuid.UUID) error
	DeleteUserPluginSettings(ctx context.Context, arg DeleteUserPluginSettingsParams) error
	DeleteUserTTSConfig(ctx context.Context, userID uuid.UUID) error
	// Sets a terminal status, ended_at, optional result_message_id /
	// result_context_id (compression sets the latter) / error_payload.
	FinalizeStreamRun(ctx context.Context, arg FinalizeStreamRunParams) (StreamRun, error)
	GetActiveContextByConversation(ctx context.Context, conversationID uuid.UUID) (Context, error)
	// Returns the (single) compression_summary message in a context, if any. Used
	// by PromoteCompactionToNewContext to read the (possibly user-edited) content
	// and seed the new context's role=context message.
	GetCompressionSummaryInContext(ctx context.Context, contextID uuid.UUID) (Message, error)
	GetContextByID(ctx context.Context, id uuid.UUID) (Context, error)
	// Row-locks the context for the duration of the enclosing transaction.
	// Used by SendMessage to serialize the
	//   resolve-parent → insert-user-message → advance-cursor
	// critical section across concurrent sends on the same context, so the
	// second SendMessage observes the first's committed state and produces
	// siblings (not a chain) when neither specifies an explicit parent.
	GetContextByIDForUpdate(ctx context.Context, id uuid.UUID) (Context, error)
	// Returns the leaf of a context's message tree: the message that no other
	// message in the same context references as a parent. When the context has
	// multiple dangling branches (shouldn't happen in normal use), returns the
	// one with the greatest id (most recently created per UUIDv7 monotonicity).
	// Returns no rows when the context is truly empty.
	// NOT EXISTS rather than NOT IN: the planner runs this as an anti-join
	// probing the messages_parent index per candidate row, where NOT IN
	// materialized the full distinct-parent set on every call (and carries
	// NULL-semantics traps besides).
	GetContextLeafMessage(ctx context.Context, contextID uuid.UUID) (Message, error)
	// Returns the (single) role=context message in a Context. Each Context has at
	// most one such message; APPEND-mode compression reads it to chain forward.
	GetContextRoleMessageInContext(ctx context.Context, contextID uuid.UUID) (Message, error)
	GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error)
	GetExplicitCache(ctx context.Context, arg GetExplicitCacheParams) (ExplicitCach, error)
	GetFile(ctx context.Context, id uuid.UUID) (File, error)
	GetFileByUserAndSHA(ctx context.Context, arg GetFileByUserAndSHAParams) (File, error)
	// Newest assistant turn in a context — the transcript seed for
	// client-invoked title generation (GenerateConversationTitle).
	GetLatestAssistantMessage(ctx context.Context, contextID uuid.UUID) (Message, error)
	// The chronological tip of a context — resolveParent's fallback when
	// no cursor is tracked. Only the id is needed; the previous
	// implementation listed the ENTIRE context (embeddings included) to
	// take the last element.
	GetLatestMessageID(ctx context.Context, contextID uuid.UUID) (uuid.UUID, error)
	// Returns the most recent stream_run for a context that recorded prefix
	// hashes (skipping turns that errored before the prefix was assembled).
	// Used by the next SendMessage to compute cache-stable prefix length.
	GetLatestStreamRunWithPrefixForContext(ctx context.Context, contextID uuid.UUID) (StreamRun, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error)
	GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error)
	GetStreamRunByID(ctx context.Context, id uuid.UUID) (StreamRun, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// Returns the user's embedder config row, if any. pgx ErrNoRows on
	// missing — callers fall back to the daemon's PSMITH_EMBEDDER env var
	// (server-default mode).
	GetUserEmbedderConfig(ctx context.Context, userID uuid.UUID) (UserEmbedderConfig, error)
	// Returns the user's Langfuse config row, if any. pgx ErrNoRows on
	// absent — service layer maps that to "tracing disabled" rather than
	// a hard error so the GET RPC can return the default-disabled shape.
	GetUserLangfuseConfig(ctx context.Context, userID uuid.UUID) (UserLangfuseConfig, error)
	GetUserMCPServer(ctx context.Context, id uuid.UUID) (UserMcpServer, error)
	GetUserModel(ctx context.Context, arg GetUserModelParams) (UserModel, error)
	GetUserModelProvider(ctx context.Context, id uuid.UUID) (UserModelProvider, error)
	// Returns the row for one (user, plugin) — caller decides what "missing"
	// means (sqlc emits ErrNoRows on no match; the service layer treats that
	// as an empty config and returns `{}` to the wire).
	GetUserPluginSettings(ctx context.Context, arg GetUserPluginSettingsParams) (UserPluginSetting, error)
	// pgx ErrNoRows on missing — callers treat absence as the apple_local
	// default (on-device synthesis, nothing to configure).
	GetUserTTSConfig(ctx context.Context, userID uuid.UUID) (UserTtsConfig, error)
	// True iff the context contains at least one role=compression_summary row that
	// did NOT fail (error_payload IS NULL). SendMessage / Compact use this as a
	// precondition: a clean pending summary must be promoted
	// (PromoteCompactionToNewContext) or deleted (DeleteMessage) before more turns
	// can land. Errored compression_summary rows are first-class history entries
	// the user can review; they do not gate the conversation — the user retries
	// by either deleting the failed summary or kicking off a fresh compaction.
	HasCompressionSummaryInContext(ctx context.Context, contextID uuid.UUID) (bool, error)
	// True iff the conversation has any stream_run with status='running'. Used by
	// the conversation-lock helper that gates mutating RPCs while a stream is
	// in flight (server-side enforcement of the UI's "disabled while streaming"
	// behavior).
	HasRunningStreamForConversation(ctx context.Context, conversationID uuid.UUID) (bool, error)
	// $4 = config_encrypted, $5 = disabled. Legacy plaintext `config`
	// column stays NULL on every new row; read path decrypts $4 and
	// falls back to the plaintext column only for the encryption-rollover
	// legacy case (which doesn't apply to a brand-new table but keeps
	// the read shape identical to profile_plugins).
	InsertConversationPlugin(ctx context.Context, arg InsertConversationPluginParams) (ConversationPlugin, error)
	// Records one cost-incurring event. Called from the stream supervisor on
	// assistant + compression_summary materialisation when total_cost_usd is
	// non-null and > 0. Errored runs still log if the provider charged
	// tokens — the user paid even if the response was junk.
	InsertCostEvent(ctx context.Context, arg InsertCostEventParams) error
	// Persist one completed device-tool call. Written by the
	// conversations service from the broker's completion hook,
	// right after the matching POST /respond returns.
	InsertDeviceToolCall(ctx context.Context, arg InsertDeviceToolCallParams) (DeviceToolCall, error)
	// $4 is config_encrypted (nullable BYTEA); the legacy plaintext
	// config column is left NULL on every new row. The service layer's
	// read path decrypts config_encrypted and falls back to the plaintext
	// column for legacy rows still carrying their pre-rollover JSONB.
	// $5 is `disabled` — when TRUE the resolver drops any same-named
	// plugin inherited from this profile's parent chain (the explicit-
	// subtract escape hatch for the merge resolver).
	InsertProfilePlugin(ctx context.Context, arg InsertProfilePluginParams) (ProfilePlugin, error)
	InsertStreamChunk(ctx context.Context, arg InsertStreamChunkParams) error
	InsertUserMCPServer(ctx context.Context, arg InsertUserMCPServerParams) (UserMcpServer, error)
	// Live runs for a specific conversation. Used by ConversationViewModel
	// on view entry to detect "there's an in-flight assistant turn the
	// previous view didn't finish receiving" — typically zero rows, at
	// most one or two (a turn + a parallel compaction).
	ListActiveStreamRunsByConversation(ctx context.Context, arg ListActiveStreamRunsByConversationParams) ([]StreamRun, error)
	// Live runs for every conversation the user owns. Powers the iOS
	// StreamHub's "what's running right now" sweep on app launch /
	// conversations-list refresh: each run gets adopted, so a cold launch
	// into a mid-generation conversation shows live content.
	ListActiveStreamRunsByUser(ctx context.Context, userID uuid.UUID) ([]StreamRun, error)
	ListAttachmentsForMessage(ctx context.Context, messageID uuid.UUID) ([]ListAttachmentsForMessageRow, error)
	// Bulk variant for history builder: one query per chain instead of N.
	ListAttachmentsForMessages(ctx context.Context, dollar_1 []uuid.UUID) ([]ListAttachmentsForMessagesRow, error)
	// Ids of childless messages in a context, capped at 2 — history
	// assembly only needs "none / exactly one / ambiguous" to preserve
	// its leafless-Build contract without listing the whole context.
	ListContextLeafIDs(ctx context.Context, contextID uuid.UUID) ([]uuid.UUID, error)
	// Per-context aggregates (message_count, last_message_total_tokens,
	// cumulative_cost_usd) are computed in a single query so the client can
	// render context-list rows without N+1 round trips.
	//
	//   last_message_total_tokens: input_tokens + output_tokens of the most
	//     recent assistant message (by created_at, then id as tiebreaker) that
	//     carries usage data. Zero when no such message exists yet. Mirrors the
	//     "last turn cost / size" UX surface — input tokens already reflect the
	//     full wire prefix at that turn, so input+output captures the work the
	//     model did for that turn.
	//   cumulative_cost_usd: SUM of messages.total_cost_usd across every row in
	//     the context (NULLs treated as zero). Includes compression_summary
	//     rows since they carry real cost.
	//
	// Lateral aggregation, not LEFT JOIN + GROUP BY: the join materialized
	// every message ROW (all columns, embeddings included) per context just
	// to count and sum two fields, then grouped by every contexts column.
	// The laterals aggregate in place off the messages(context_id, ...)
	// indexes and only two scalars leave each subquery. The client
	// refreshes this list after every terminal and delete, so it runs
	// constantly on hot conversations.
	ListContextsByConversation(ctx context.Context, conversationID uuid.UUID) ([]ListContextsByConversationRow, error)
	// Plugin pipeline overrides scoped to one conversation. Merged on
	// top of the profile-chain plugins at resolve time — see
	// internal/conversations/service.resolvePluginPipeline.
	ListConversationPlugins(ctx context.Context, conversationID uuid.UUID) ([]ConversationPlugin, error)
	ListConversationsByUser(ctx context.Context, userID uuid.UUID) ([]Conversation, error)
	// Same filters as ListConversationsByUserRecentlyUsed but ordered by the
	// conversation's own created_at — the freshest creation always wins
	// regardless of subsequent message traffic. Still computes
	// last_activity_at for clients that want to display "last used" alongside
	// the row even when sorting by creation. Same keyset scheme, keyed on
	// created_at.
	ListConversationsByUserRecentlyCreated(ctx context.Context, arg ListConversationsByUserRecentlyCreatedParams) ([]ListConversationsByUserRecentlyCreatedRow, error)
	// Returns conversations sorted by the most recent message activity, with
	// created_at as the fallback for conversations that haven't received a
	// message yet. Optional filters: case-insensitive title substring (NULL
	// skips the filter; conversations with no title are excluded when set);
	// profile_id (NULL skips the filter).
	//
	// Keyset paging: cursor_key/cursor_id (NULL = first page) resume after
	// the row with that (last_activity_at, id) tuple; id breaks timestamp
	// ties so a page boundary through same-instant rows can't skip or
	// duplicate. page_limit callers pass limit+1 to detect a next page.
	ListConversationsByUserRecentlyUsed(ctx context.Context, arg ListConversationsByUserRecentlyUsedParams) ([]ListConversationsByUserRecentlyUsedRow, error)
	// Same shape as ListDeviceToolCallsByUser, scoped to one
	// conversation. The handler verifies the caller owns the
	// conversation before running this — there's no per-row user_id
	// guard in this query itself.
	ListDeviceToolCallsByConversation(ctx context.Context, arg ListDeviceToolCallsByConversationParams) ([]DeviceToolCall, error)
	// Recent-first paginated list for the Settings → Device tool
	// activity page. `before` is the cutoff: pass NOW() for the first
	// page, the invoked_at of the last row from the previous page for
	// subsequent pages. Always-set timestamp avoids nullable-param
	// gymnastics around an optional cursor.
	ListDeviceToolCallsByUser(ctx context.Context, arg ListDeviceToolCallsByUserParams) ([]DeviceToolCall, error)
	ListFilesForUser(ctx context.Context, arg ListFilesForUserParams) ([]File, error)
	// Walks parent_id from the leaf back to the root, returning rows root-first.
	// sibling_count: number of OTHER messages sharing this row's parent — i.e.
	// branches forking off the same parent. The UI uses it to render fork
	// indicators alongside the linear chain.
	ListMessageAncestorChain(ctx context.Context, id uuid.UUID) ([]ListMessageAncestorChainRow, error)
	// The ancestor chain of a leaf as FULL message rows (message_headers /
	// message_trailers included — the wire envelope needs them), returned
	// root-first. History assembly runs on every send and every token
	// count; this is O(chain) where ListMessagesByContext is O(context),
	// and forked contexts carry dead branches the chain never touches.
	ListMessageChainForHistory(ctx context.Context, id uuid.UUID) ([]ListMessageChainForHistoryRow, error)
	// Skeleton rows for the branch switcher: the tree SHAPE without
	// content. Selecting only these columns keeps TOASTed message bodies
	// entirely unread.
	ListMessageTreeStructure(ctx context.Context, contextID uuid.UUID) ([]ListMessageTreeStructureRow, error)
	ListMessagesByContext(ctx context.Context, contextID uuid.UUID) ([]Message, error)
	// When the user swaps embedders (different Model() than what's on
	// existing rows), backfill re-embeds. Returns the rows that need
	// re-embedding under the new model. Like ListUnembeddedMessages but
	// the predicate is "wrong model" rather than "no embedding."
	ListMessagesEmbeddedUnderDifferentModel(ctx context.Context, arg ListMessagesEmbeddedUnderDifferentModelParams) ([]ListMessagesEmbeddedUnderDifferentModelRow, error)
	// The pinned block served ahead of page one. Same filters as the paged
	// queries; never paged itself (pins are few; LIMIT 100 is a guardrail,
	// matching MaxListPageSize). Every pinned row is active by invariant,
	// but the archived filter keeps the archived listing honest anyway.
	ListPinnedConversationsByUser(ctx context.Context, arg ListPinnedConversationsByUserParams) ([]ListPinnedConversationsByUserRow, error)
	// Returns the ordered plugin pipeline for one profile (no inheritance walk;
	// callers do the walk in code so they can short-circuit on a profile that
	// defines its own pipeline).
	ListProfilePlugins(ctx context.Context, profileID uuid.UUID) ([]ProfilePlugin, error)
	ListProfilesByUser(ctx context.Context, userID uuid.UUID) ([]Profile, error)
	// Keyset-paged variant: ascending (created_at, id), cursor resumes after
	// that tuple. Callers pass page_limit = limit+1 to detect a next page.
	// The unpaged query above stays for page_size=0 (legacy return-all).
	ListProfilesByUserPaged(ctx context.Context, arg ListProfilesByUserPagedParams) ([]Profile, error)
	// Per-provider running totals across the ledger, optionally bounded by
	// a [since, until) occurred_at window. Drives the iOS Settings → Cost
	// screen — one row per configured provider, single dollar amount per
	// row. Sorted alphabetically by the provider's label so the list reads
	// stably across reloads. Providers with no events in the window are
	// still surfaced (LEFT JOIN with the window predicate in the JOIN ON,
	// not the WHERE — putting it in WHERE would silently drop them).
	ListProviderCostTotals(ctx context.Context, arg ListProviderCostTotalsParams) ([]ListProviderCostTotalsRow, error)
	// Returns persisted chunks for a run, in sequence order, starting at the given
	// sequence cursor. Used to replay missed chunks for late subscribers.
	ListStreamChunks(ctx context.Context, arg ListStreamChunksParams) ([]StreamChunk, error)
	ListStreamRunsByConversation(ctx context.Context, conversationID uuid.UUID) ([]StreamRun, error)
	// Backfill worker's hot path. Skips system messages (framing, not
	// searchable content) and zero-length rows (nothing to embed). Ordered
	// by user_id (so the worker can group within a batch and dispatch one
	// embedder call per user) then oldest-first within the user — partial
	// backfill makes monotonic progress against `created_at` and the
	// "embedded up to YYYY-MM-DD" chip stays accurate.
	ListUnembeddedMessages(ctx context.Context, limit int32) ([]ListUnembeddedMessagesRow, error)
	// IDs of users who haven't had the system profile templates seeded yet.
	// Drives the server-startup backfill so existing users get the new templates
	// on next restart without waiting for a login.
	ListUnseededUserIDs(ctx context.Context) ([]uuid.UUID, error)
	// The worker enumerates this to know which users have configured
	// embedders. Returning all rows in one shot is fine — we'd never
	// have more than a handful per Psmith instance.
	ListUserEmbedderConfigs(ctx context.Context) ([]UserEmbedderConfig, error)
	// Every existing row across all users. Used at server boot to prime
	// the in-memory emitter cache so tracing works for the very first
	// assistant turn after a restart, not just after the first
	// LangfuseService.Update RPC of the new process.
	ListUserLangfuseConfigs(ctx context.Context) ([]UserLangfuseConfig, error)
	ListUserMCPServers(ctx context.Context, userID uuid.UUID) ([]UserMcpServer, error)
	ListUserModelProvidersByUser(ctx context.Context, userID uuid.UUID) ([]UserModelProvider, error)
	ListUserModelsByProvider(ctx context.Context, userModelProviderID uuid.UUID) ([]UserModel, error)
	ListUserModelsByUser(ctx context.Context, userID uuid.UUID) ([]UserModel, error)
	// All globally-configured plugins for a user. Drives the "Plugin
	// settings" page; missing rows mean "not yet configured" and need a
	// defaults-from-descriptor render at the UI layer.
	ListUserPluginSettings(ctx context.Context, userID uuid.UUID) ([]UserPluginSetting, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkDefaultProfile(ctx context.Context, id uuid.UUID) error
	// Called once on server boot. The upstream sockets died with the process and
	// cannot be resumed; users see a partial assistant message + retry affordance.
	MarkRunningAsInterrupted(ctx context.Context) error
	MarkSystemProfilesSeeded(ctx context.Context, id uuid.UUID) error
	// Returns the highest persisted sequence for a run, or NULL if none persisted.
	MaxStreamChunkSequence(ctx context.Context, streamRunID uuid.UUID) (int64, error)
	// Deletes stream_chunks belonging to stream_runs that finalized more
	// than $1 ago. Stream chunks are transient — they exist only to feed
	// mid-stream subscribers (and to let late reconnects within the
	// retention window catch up). Once a run is finalized, the assistant
	// message row carries the persisted aggregate; the per-chunk rows
	// become dead weight.
	//
	// Uses a CTE rather than a JOIN so the planner picks the indexed
	// (ended_at) scan on stream_runs as the driver. Returns the number of
	// chunk rows pruned so the caller can log a trickle of housekeeping
	// activity (or skip the log entirely on zero-row runs).
	PruneFinalizedStreamChunks(ctx context.Context, retention pgtype.Interval) (int64, error)
	// Points children of a context about to be deleted at their
	// grandparent, keeping compaction lineage connected. NULL parent is
	// valid (the deleted context was a root).
	ReparentChildContexts(ctx context.Context, arg ReparentChildContextsParams) error
	// Promotes every direct child of $1 to point at $2 (which may be NULL — that
	// makes them roots in the context). Used by DeleteMessage(cascade=false) just
	// before the DELETE, so the FK's ON DELETE CASCADE has nothing to find.
	ReparentChildren(ctx context.Context, arg ReparentChildrenParams) error
	// Atomic-swap pattern matching profile_plugins. Caller wraps this in
	// a transaction together with per-row InsertConversationPlugin calls.
	ReplaceConversationPlugins(ctx context.Context, conversationID uuid.UUID) error
	// Atomically swap the pipeline. Caller wraps this in a transaction along with
	// the per-row inserts via InsertProfilePlugin (an in-tx loop) — there's no
	// batch-insert sqlc emit for an arbitrary slice.
	ReplaceProfilePlugins(ctx context.Context, profileID uuid.UUID) error
	// Cosine-distance ranked search. Restricts to messages owned by the
	// caller (via the context→conversation→user chain) and to rows
	// embedded under the same model as the query vector — mixing models
	// would compare vectors from different spaces and yield garbage.
	//
	// Returns m.context_id alongside m.id so the memory plugin can drop
	// hits that are still in the wire prefix. A conversation is a
	// SEQUENCE of contexts: when compression fires, the old context is
	// retired and a new one becomes active. The wire prefix is only ever
	// built from the active context, so messages from old contexts —
	// even in the SAME conversation as the caller — are exactly the
	// "no longer in scope" content the memory plugin should surface.
	//
	// `<=>` is pgvector's cosine-distance operator: 0 = identical
	// direction, 2 = opposite. Smaller is better. We surface the raw
	// distance so callers can threshold ("only return matches under 0.4").
	//
	// pgvector's HNSW index handles ORDER BY ... LIMIT efficiently even
	// with the WHERE filter, provided the filter is selective enough to
	// not prune away most candidates. For a single user that's free; if
	// we ever scale to many users per Psmith instance the index would
	// need partitioning, but that's a future-us problem.
	SearchMessagesByEmbedding(ctx context.Context, arg SearchMessagesByEmbeddingParams) ([]SearchMessagesByEmbeddingRow, error)
	// Archive (TRUE → archived_at = now()) or unarchive (FALSE → NULL).
	// Archiving also clears the pin: pinned is an active-list concept, and
	// keeping them exclusive means every pinned row is an active row (the
	// list queries rely on that invariant).
	SetConversationArchived(ctx context.Context, arg SetConversationArchivedParams) error
	SetConversationPinned(ctx context.Context, arg SetConversationPinnedParams) error
	// Worker writes the embedding triple. Idempotent: the CHECK constraint
	// enforces all-three-or-none on every row already, so calling with the
	// same triple over and over is fine.
	SetMessageEmbedding(ctx context.Context, arg SetMessageEmbeddingParams) error
	// Records the per-message hashes of the rendered wire-prefix for a run plus
	// the diagnostics computed against the previous turn (NULL on the first
	// turn for a context — no comparison possible).
	SetStreamRunPrefixHashes(ctx context.Context, arg SetStreamRunPrefixHashesParams) error
	SetUserModelFavorite(ctx context.Context, arg SetUserModelFavoriteParams) error
	// Bump the coarse mutation stamp without changing any field. Message
	// edits and deletes call this so clients' cheap staleness check
	// (compare updated_at + active context + leaf) can detect content
	// mutations that move neither the leaf nor any conversation column.
	TouchConversationUpdatedAt(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, tokenHash string) error
	UpdateContextActivationTime(ctx context.Context, arg UpdateContextActivationTimeParams) (Context, error)
	// Sets the per-context cursor for "the tip the user is currently viewing."
	// Pass NULL for current_leaf_message_id to clear the cursor.
	UpdateContextCurrentLeaf(ctx context.Context, arg UpdateContextCurrentLeafParams) (Context, error)
	// Sets the human-friendly title for a Context. Pass NULL to clear.
	// Populated automatically after the first assistant turn lands in the
	// context (when profile title settings are configured); editable by user.
	UpdateContextTitle(ctx context.Context, arg UpdateContextTitleParams) error
	UpdateConversationSettings(ctx context.Context, arg UpdateConversationSettingsParams) error
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error
	// In-place edit. content is always set; role is COALESCE'd so the caller can
	// pass NULL to leave it unchanged. edited_at = NOW() unconditionally.
	// sqlc.narg lets the role param be nullable (sqlc otherwise infers
	// non-nullable from the column type).
	UpdateMessageContentRole(ctx context.Context, arg UpdateMessageContentRoleParams) (Message, error)
	UpdateProfileCompressionGuide(ctx context.Context, arg UpdateProfileCompressionGuideParams) error
	UpdateProfileCompressionMode(ctx context.Context, arg UpdateProfileCompressionModeParams) error
	UpdateProfileCompressionModelID(ctx context.Context, arg UpdateProfileCompressionModelIDParams) error
	UpdateProfileCompressionProviderID(ctx context.Context, arg UpdateProfileCompressionProviderIDParams) error
	UpdateProfileDefaultSettings(ctx context.Context, arg UpdateProfileDefaultSettingsParams) error
	UpdateProfileDefaultUserMessage(ctx context.Context, arg UpdateProfileDefaultUserMessageParams) error
	UpdateProfileDescription(ctx context.Context, arg UpdateProfileDescriptionParams) error
	UpdateProfileFavorite(ctx context.Context, arg UpdateProfileFavoriteParams) error
	UpdateProfileName(ctx context.Context, arg UpdateProfileNameParams) error
	UpdateProfileParentOnly(ctx context.Context, arg UpdateProfileParentOnlyParams) error
	UpdateProfileParentProfileID(ctx context.Context, arg UpdateProfileParentProfileIDParams) error
	// Overwrite the encrypted config for one plugin entry in a profile's
	// pipeline. Also clears the legacy plaintext column so a read can't
	// accidentally fall back to it after an upgrade. Used by the system-
	// profile backfill to repair stale configs left over from older seed
	// versions; ordinary plugin edits go through ReplaceProfilePlugins +
	// InsertProfilePlugin (atomic whole-pipeline swap).
	UpdateProfilePluginConfig(ctx context.Context, arg UpdateProfilePluginConfigParams) error
	UpdateProfileSystemMessage(ctx context.Context, arg UpdateProfileSystemMessageParams) error
	UpdateProfileTitleGuide(ctx context.Context, arg UpdateProfileTitleGuideParams) error
	UpdateProfileTitleModelID(ctx context.Context, arg UpdateProfileTitleModelIDParams) error
	UpdateProfileTitleProviderID(ctx context.Context, arg UpdateProfileTitleProviderIDParams) error
	UpdateProfileTitleProviderKind(ctx context.Context, arg UpdateProfileTitleProviderKindParams) error
	UpdateProfileWelcomeMessage(ctx context.Context, arg UpdateProfileWelcomeMessageParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserIsAdmin(ctx context.Context, arg UpdateUserIsAdminParams) error
	UpdateUserMCPServer(ctx context.Context, arg UpdateUserMCPServerParams) (UserMcpServer, error)
	// Replaces (not merges) the per-model default_settings JSONB blob. NULL
	// clears it. metadata_snapshot_at is bumped so consumers polling for row
	// changes notice the update — the row's metadata identity hasn't changed,
	// but its effective behavior has.
	UpdateUserModelDefaultSettings(ctx context.Context, arg UpdateUserModelDefaultSettingsParams) error
	// Replaces (not merges) the provider-level default_settings blob. NULL clears
	// it, returning the row to "no provider-level defaults; resolve from above
	// only." Replace semantics keep the call site simple — the resolver does the
	// merge with the upper layers, so partial writes here would be a footgun.
	UpdateUserModelProviderDefaultSettings(ctx context.Context, arg UpdateUserModelProviderDefaultSettingsParams) error
	// Full-replacement update on the encrypted column. The service layer
	// handles partial-merge semantics in Go (decrypt → JSON merge →
	// re-encrypt) before calling this — the SQL side stays straightforward
	// replacement so the encrypted bytes remain a single sealed unit.
	// Clears any plaintext config that may still be present, finalising
	// the row's transition to encrypted-only storage.
	UpdateUserModelProviderEncryptedConfig(ctx context.Context, arg UpdateUserModelProviderEncryptedConfigParams) error
	UpdateUserModelProviderLabel(ctx context.Context, arg UpdateUserModelProviderLabelParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertExplicitCache(ctx context.Context, arg UpsertExplicitCacheParams) error
	// Single-row upsert keyed by user_id. Conflict resolves by replacing
	// every field (no merge semantics) — the UI sends the whole row each
	// time and "clear my api_key" must work via an empty bytea.
	UpsertUserEmbedderConfig(ctx context.Context, arg UpsertUserEmbedderConfigParams) (UserEmbedderConfig, error)
	// Single-call full replace. The service layer reads the existing row
	// (if any), merges request fields onto it, then calls this — same
	// pattern as UpdateUserModel. secret_key_encrypted is the only
	// credential column; the value is AES-GCM encrypted before it
	// reaches this query (see internal/langfusesvc).
	UpsertUserLangfuseConfig(ctx context.Context, arg UpsertUserLangfuseConfigParams) (UserLangfuseConfig, error)
	UpsertUserModel(ctx context.Context, arg UpsertUserModelParams) (UserModel, error)
	// Idempotent: insert-or-update. updated_at is bumped to NOW() on every
	// save. Empty config (encrypted form of `{}`) is a valid stored value
	// — it means "the user explicitly cleared every global field" and
	// should beat the absence-is-empty fallback at merge time.
	//
	// Writes to config_encrypted only and clears any plaintext config left
	// behind from before the encryption rollout. The service layer
	// decrypts incoming reads and falls back to plaintext when
	// config_encrypted is NULL on legacy rows.
	UpsertUserPluginSettings(ctx context.Context, arg UpsertUserPluginSettingsParams) (UserPluginSetting, error)
	// Single-row upsert keyed by user_id; conflict replaces every field
	// (the service sparse-merges before calling, and "clear my api_key"
	// must work via an empty bytea).
	UpsertUserTTSConfig(ctx context.Context, arg UpsertUserTTSConfigParams) (UserTtsConfig, error)
}

var _ Querier = (*Queries)(nil)
