// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CountCatalogModels(ctx context.Context) (int64, error)
	CountCatalogProviders(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// Used by the stream supervisor at materialization. Allows the assistant turn
	// (or the compression_summary record) to be inserted with usage + cost
	// columns populated atomically. error_payload is set when the stream
	// terminated in an errored/cancelled state — captures the failure inline so
	// the UI can render the message as a first-class errored history entry.
	// thinking_duration_ms records the elapsed time (ms) between the first and
	// last thinking_delta chunk seen on the run; NULL when the assistant didn't
	// reason at all.
	CreateAssistantMessageWithUsage(ctx context.Context, arg CreateAssistantMessageWithUsageParams) (Message, error)
	CreateContext(ctx context.Context, arg CreateContextParams) (Context, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateStreamRun(ctx context.Context, arg CreateStreamRunParams) (StreamRun, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserModelProvider(ctx context.Context, arg CreateUserModelProviderParams) (UserModelProvider, error)
	DeleteConversation(ctx context.Context, id uuid.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	// The cascade=true path. With ON DELETE CASCADE on parent_id (migration 00006),
	// this single DELETE removes the descendant subtree too.
	DeleteMessageByID(ctx context.Context, id uuid.UUID) error
	DeleteProfile(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, tokenHash string) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserModel(ctx context.Context, arg DeleteUserModelParams) error
	DeleteUserModelProvider(ctx context.Context, id uuid.UUID) error
	// Sets a terminal status, ended_at, optional result_message_id /
	// result_context_id (compression sets the latter) / error_payload.
	FinalizeStreamRun(ctx context.Context, arg FinalizeStreamRunParams) (StreamRun, error)
	GetActiveContextByConversation(ctx context.Context, conversationID uuid.UUID) (Context, error)
	GetCatalogModel(ctx context.Context, arg GetCatalogModelParams) (CatalogModel, error)
	GetCatalogProvider(ctx context.Context, id string) (CatalogModelProvider, error)
	// Returns the (single) compression_summary message in a context, if any. Used
	// by PromoteCompactionToNewContext to read the (possibly user-edited) content
	// and seed the new context's role=context message.
	GetCompressionSummaryInContext(ctx context.Context, contextID uuid.UUID) (Message, error)
	GetContextByID(ctx context.Context, id uuid.UUID) (Context, error)
	// Row-locks the context for the duration of the enclosing transaction.
	// Used by SendMessage to serialize the
	//   resolve-parent → insert-user-message → advance-cursor
	// critical section across concurrent sends on the same context, so the
	// second SendMessage observes the first's committed state and produces
	// siblings (not a chain) when neither specifies an explicit parent.
	GetContextByIDForUpdate(ctx context.Context, id uuid.UUID) (Context, error)
	// Returns the leaf of a context's message tree: the message that no other
	// message in the same context references as a parent. When the context has
	// multiple dangling branches (shouldn't happen in normal use), returns the
	// one with the greatest id (most recently created per UUIDv7 monotonicity).
	// Returns no rows when the context is truly empty.
	GetContextLeafMessage(ctx context.Context, contextID uuid.UUID) (Message, error)
	// Returns the (single) role=context message in a Context. Each Context has at
	// most one such message; APPEND-mode compression reads it to chain forward.
	GetContextRoleMessageInContext(ctx context.Context, contextID uuid.UUID) (Message, error)
	GetConversationByID(ctx context.Context, id uuid.UUID) (Conversation, error)
	// Returns the most recent stream_run for a context that recorded prefix
	// hashes (skipping turns that errored before the prefix was assembled).
	// Used by the next SendMessage to compute cache-stable prefix length.
	GetLatestStreamRunWithPrefixForContext(ctx context.Context, contextID uuid.UUID) (StreamRun, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error)
	GetSessionWithUser(ctx context.Context, tokenHash string) (GetSessionWithUserRow, error)
	GetStreamRunByID(ctx context.Context, id uuid.UUID) (StreamRun, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserModel(ctx context.Context, arg GetUserModelParams) (UserModel, error)
	GetUserModelProvider(ctx context.Context, id uuid.UUID) (UserModelProvider, error)
	// True iff the context contains at least one role=compression_summary row that
	// did NOT fail (error_payload IS NULL). SendMessage / Compact use this as a
	// precondition: a clean pending summary must be promoted
	// (PromoteCompactionToNewContext) or deleted (DeleteMessage) before more turns
	// can land. Errored compression_summary rows are first-class history entries
	// the user can review; they do not gate the conversation — the user retries
	// by either deleting the failed summary or kicking off a fresh compaction.
	HasCompressionSummaryInContext(ctx context.Context, contextID uuid.UUID) (bool, error)
	// True iff the conversation has any stream_run with status='running'. Used by
	// the conversation-lock helper that gates mutating RPCs while a stream is
	// in flight (server-side enforcement of the UI's "disabled while streaming"
	// behavior).
	HasRunningStreamForConversation(ctx context.Context, conversationID uuid.UUID) (bool, error)
	InsertProfilePlugin(ctx context.Context, arg InsertProfilePluginParams) (ProfilePlugin, error)
	InsertStreamChunk(ctx context.Context, arg InsertStreamChunkParams) error
	LatestCatalogFetch(ctx context.Context) (time.Time, error)
	ListCatalogModelsByProvider(ctx context.Context, providerID string) ([]CatalogModel, error)
	ListCatalogProviders(ctx context.Context) ([]CatalogModelProvider, error)
	// Per-context aggregates (message_count, last_message_total_tokens,
	// cumulative_cost_usd) are computed in a single query so the client can
	// render context-list rows without N+1 round trips.
	//
	//   last_message_total_tokens: input_tokens + output_tokens of the most
	//     recent assistant message (by created_at, then id as tiebreaker) that
	//     carries usage data. Zero when no such message exists yet. Mirrors the
	//     "last turn cost / size" UX surface — input tokens already reflect the
	//     full wire prefix at that turn, so input+output captures the work the
	//     model did for that turn.
	//   cumulative_cost_usd: SUM of messages.total_cost_usd across every row in
	//     the context (NULLs treated as zero). Includes compression_summary
	//     rows since they carry real cost.
	ListContextsByConversation(ctx context.Context, conversationID uuid.UUID) ([]ListContextsByConversationRow, error)
	ListConversationsByUser(ctx context.Context, userID uuid.UUID) ([]Conversation, error)
	// Same filters as ListConversationsByUserRecentlyUsed but ordered by the
	// conversation's own created_at — the freshest creation always wins
	// regardless of subsequent message traffic. Still computes
	// last_activity_at for clients that want to display "last used" alongside
	// the row even when sorting by creation.
	ListConversationsByUserRecentlyCreated(ctx context.Context, arg ListConversationsByUserRecentlyCreatedParams) ([]ListConversationsByUserRecentlyCreatedRow, error)
	// Returns conversations sorted by the most recent message activity, with
	// created_at as the fallback for conversations that haven't received a
	// message yet. Optional filters: case-insensitive title substring (NULL
	// skips the filter; conversations with no title are excluded when set);
	// profile_id (NULL skips the filter).
	ListConversationsByUserRecentlyUsed(ctx context.Context, arg ListConversationsByUserRecentlyUsedParams) ([]ListConversationsByUserRecentlyUsedRow, error)
	// Walks parent_id from the leaf back to the root, returning rows root-first.
	// sibling_count: number of OTHER messages sharing this row's parent — i.e.
	// branches forking off the same parent. The UI uses it to render fork
	// indicators alongside the linear chain.
	ListMessageAncestorChain(ctx context.Context, id uuid.UUID) ([]ListMessageAncestorChainRow, error)
	ListMessagesByContext(ctx context.Context, contextID uuid.UUID) ([]Message, error)
	// Returns the ordered plugin pipeline for one profile (no inheritance walk;
	// callers do the walk in code so they can short-circuit on a profile that
	// defines its own pipeline).
	ListProfilePlugins(ctx context.Context, profileID uuid.UUID) ([]ProfilePlugin, error)
	ListProfilesByUser(ctx context.Context, userID uuid.UUID) ([]Profile, error)
	// Returns persisted chunks for a run, in sequence order, starting at the given
	// sequence cursor. Used to replay missed chunks for late subscribers.
	ListStreamChunks(ctx context.Context, arg ListStreamChunksParams) ([]StreamChunk, error)
	ListStreamRunsByConversation(ctx context.Context, conversationID uuid.UUID) ([]StreamRun, error)
	ListUserModelProvidersByUser(ctx context.Context, userID uuid.UUID) ([]UserModelProvider, error)
	ListUserModelsByProvider(ctx context.Context, userModelProviderID uuid.UUID) ([]UserModel, error)
	ListUserModelsByUser(ctx context.Context, userID uuid.UUID) ([]UserModel, error)
	ListUsers(ctx context.Context) ([]User, error)
	// Called once on server boot. The upstream sockets died with the process and
	// cannot be resumed; users see a partial assistant message + retry affordance.
	MarkRunningAsInterrupted(ctx context.Context) error
	// Returns the highest persisted sequence for a run, or NULL if none persisted.
	MaxStreamChunkSequence(ctx context.Context, streamRunID uuid.UUID) (int64, error)
	// Promotes every direct child of $1 to point at $2 (which may be NULL — that
	// makes them roots in the context). Used by DeleteMessage(cascade=false) just
	// before the DELETE, so the FK's ON DELETE CASCADE has nothing to find.
	ReparentChildren(ctx context.Context, arg ReparentChildrenParams) error
	// Atomically swap the pipeline. Caller wraps this in a transaction along with
	// the per-row inserts via InsertProfilePlugin (an in-tx loop) — there's no
	// batch-insert sqlc emit for an arbitrary slice.
	ReplaceProfilePlugins(ctx context.Context, profileID uuid.UUID) error
	// Records the per-message hashes of the rendered wire-prefix for a run plus
	// the diagnostics computed against the previous turn (NULL on the first
	// turn for a context — no comparison possible).
	SetStreamRunPrefixHashes(ctx context.Context, arg SetStreamRunPrefixHashesParams) error
	SetUserModelFavorite(ctx context.Context, arg SetUserModelFavoriteParams) error
	TouchSession(ctx context.Context, tokenHash string) error
	UpdateContextActivationTime(ctx context.Context, arg UpdateContextActivationTimeParams) (Context, error)
	// Sets the per-context cursor for "the tip the user is currently viewing."
	// Pass NULL for current_leaf_message_id to clear the cursor.
	UpdateContextCurrentLeaf(ctx context.Context, arg UpdateContextCurrentLeafParams) (Context, error)
	// Sets the human-friendly title for a Context. Pass NULL to clear.
	// Populated automatically after the first assistant turn lands in the
	// context (when profile title settings are configured); editable by user.
	UpdateContextTitle(ctx context.Context, arg UpdateContextTitleParams) error
	UpdateConversationSettings(ctx context.Context, arg UpdateConversationSettingsParams) error
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error
	// In-place edit. content is always set; role is COALESCE'd so the caller can
	// pass NULL to leave it unchanged. edited_at = NOW() unconditionally.
	// sqlc.narg lets the role param be nullable (sqlc otherwise infers
	// non-nullable from the column type).
	UpdateMessageContentRole(ctx context.Context, arg UpdateMessageContentRoleParams) (Message, error)
	UpdateProfileCompressionGuide(ctx context.Context, arg UpdateProfileCompressionGuideParams) error
	UpdateProfileCompressionMode(ctx context.Context, arg UpdateProfileCompressionModeParams) error
	UpdateProfileCompressionModelID(ctx context.Context, arg UpdateProfileCompressionModelIDParams) error
	UpdateProfileCompressionProviderID(ctx context.Context, arg UpdateProfileCompressionProviderIDParams) error
	UpdateProfileDefaultSettings(ctx context.Context, arg UpdateProfileDefaultSettingsParams) error
	UpdateProfileDefaultUserMessage(ctx context.Context, arg UpdateProfileDefaultUserMessageParams) error
	UpdateProfileDescription(ctx context.Context, arg UpdateProfileDescriptionParams) error
	UpdateProfileFavorite(ctx context.Context, arg UpdateProfileFavoriteParams) error
	UpdateProfileName(ctx context.Context, arg UpdateProfileNameParams) error
	UpdateProfileParentOnly(ctx context.Context, arg UpdateProfileParentOnlyParams) error
	UpdateProfileSystemMessage(ctx context.Context, arg UpdateProfileSystemMessageParams) error
	UpdateProfileTitleGuide(ctx context.Context, arg UpdateProfileTitleGuideParams) error
	UpdateProfileTitleModelID(ctx context.Context, arg UpdateProfileTitleModelIDParams) error
	UpdateProfileTitleProviderID(ctx context.Context, arg UpdateProfileTitleProviderIDParams) error
	UpdateProfileTitleProviderKind(ctx context.Context, arg UpdateProfileTitleProviderKindParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserIsAdmin(ctx context.Context, arg UpdateUserIsAdminParams) error
	// Replaces (not merges) the per-model default_settings JSONB blob. NULL
	// clears it. metadata_snapshot_at is bumped so consumers polling for row
	// changes notice the update — the row's metadata identity hasn't changed,
	// but its effective behavior has.
	UpdateUserModelDefaultSettings(ctx context.Context, arg UpdateUserModelDefaultSettingsParams) error
	// Shallow-merges the incoming JSONB patch into the existing config. Keys
	// present in the patch override existing values; absent keys are preserved.
	// To clear a key, send it explicitly with an empty value.
	UpdateUserModelProviderConfig(ctx context.Context, arg UpdateUserModelProviderConfigParams) error
	// Replaces (not merges) the provider-level default_settings blob. NULL clears
	// it, returning the row to "no provider-level defaults; resolve from above
	// only." Replace semantics keep the call site simple — the resolver does the
	// merge with the upper layers, so partial writes here would be a footgun.
	UpdateUserModelProviderDefaultSettings(ctx context.Context, arg UpdateUserModelProviderDefaultSettingsParams) error
	UpdateUserModelProviderLabel(ctx context.Context, arg UpdateUserModelProviderLabelParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Catalog models -----------------------------------------------------------
	UpsertCatalogModel(ctx context.Context, arg UpsertCatalogModelParams) error
	// Catalog providers --------------------------------------------------------
	UpsertCatalogProvider(ctx context.Context, arg UpsertCatalogProviderParams) error
	UpsertUserModel(ctx context.Context, arg UpsertUserModelParams) (UserModel, error)
}

var _ Querier = (*Queries)(nil)
