// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: streams.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createStreamRun = `-- name: CreateStreamRun :one
INSERT INTO stream_runs (
    id, conversation_id, context_id, parent_message_id,
    provider_id, model_id, status, purpose
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
RETURNING id, conversation_id, context_id, parent_message_id, provider_id, model_id, status, purpose, started_at, ended_at, error_payload, result_message_id, result_context_id, prefix_hashes, prefix_length, cache_stable_prefix_length, cache_trailing_depth
`

type CreateStreamRunParams struct {
	ID              uuid.UUID
	ConversationID  uuid.UUID
	ContextID       uuid.UUID
	ParentMessageID *uuid.UUID
	ProviderID      uuid.UUID
	ModelID         string
	Status          string
	Purpose         string
}

func (q *Queries) CreateStreamRun(ctx context.Context, arg CreateStreamRunParams) (StreamRun, error) {
	row := q.db.QueryRow(ctx, createStreamRun,
		arg.ID,
		arg.ConversationID,
		arg.ContextID,
		arg.ParentMessageID,
		arg.ProviderID,
		arg.ModelID,
		arg.Status,
		arg.Purpose,
	)
	var i StreamRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ContextID,
		&i.ParentMessageID,
		&i.ProviderID,
		&i.ModelID,
		&i.Status,
		&i.Purpose,
		&i.StartedAt,
		&i.EndedAt,
		&i.ErrorPayload,
		&i.ResultMessageID,
		&i.ResultContextID,
		&i.PrefixHashes,
		&i.PrefixLength,
		&i.CacheStablePrefixLength,
		&i.CacheTrailingDepth,
	)
	return i, err
}

const finalizeStreamRun = `-- name: FinalizeStreamRun :one
UPDATE stream_runs
SET status = $2,
    ended_at = NOW(),
    result_message_id = $3,
    result_context_id = $4,
    error_payload = $5
WHERE id = $1
RETURNING id, conversation_id, context_id, parent_message_id, provider_id, model_id, status, purpose, started_at, ended_at, error_payload, result_message_id, result_context_id, prefix_hashes, prefix_length, cache_stable_prefix_length, cache_trailing_depth
`

type FinalizeStreamRunParams struct {
	ID              uuid.UUID
	Status          string
	ResultMessageID *uuid.UUID
	ResultContextID *uuid.UUID
	ErrorPayload    []byte
}

// Sets a terminal status, ended_at, optional result_message_id /
// result_context_id (compression sets the latter) / error_payload.
func (q *Queries) FinalizeStreamRun(ctx context.Context, arg FinalizeStreamRunParams) (StreamRun, error) {
	row := q.db.QueryRow(ctx, finalizeStreamRun,
		arg.ID,
		arg.Status,
		arg.ResultMessageID,
		arg.ResultContextID,
		arg.ErrorPayload,
	)
	var i StreamRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ContextID,
		&i.ParentMessageID,
		&i.ProviderID,
		&i.ModelID,
		&i.Status,
		&i.Purpose,
		&i.StartedAt,
		&i.EndedAt,
		&i.ErrorPayload,
		&i.ResultMessageID,
		&i.ResultContextID,
		&i.PrefixHashes,
		&i.PrefixLength,
		&i.CacheStablePrefixLength,
		&i.CacheTrailingDepth,
	)
	return i, err
}

const getLatestStreamRunWithPrefixForContext = `-- name: GetLatestStreamRunWithPrefixForContext :one
SELECT id, conversation_id, context_id, parent_message_id, provider_id, model_id, status, purpose, started_at, ended_at, error_payload, result_message_id, result_context_id, prefix_hashes, prefix_length, cache_stable_prefix_length, cache_trailing_depth FROM stream_runs
WHERE context_id = $1 AND prefix_hashes IS NOT NULL
ORDER BY started_at DESC
LIMIT 1
`

// Returns the most recent stream_run for a context that recorded prefix
// hashes (skipping turns that errored before the prefix was assembled).
// Used by the next SendMessage to compute cache-stable prefix length.
func (q *Queries) GetLatestStreamRunWithPrefixForContext(ctx context.Context, contextID uuid.UUID) (StreamRun, error) {
	row := q.db.QueryRow(ctx, getLatestStreamRunWithPrefixForContext, contextID)
	var i StreamRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ContextID,
		&i.ParentMessageID,
		&i.ProviderID,
		&i.ModelID,
		&i.Status,
		&i.Purpose,
		&i.StartedAt,
		&i.EndedAt,
		&i.ErrorPayload,
		&i.ResultMessageID,
		&i.ResultContextID,
		&i.PrefixHashes,
		&i.PrefixLength,
		&i.CacheStablePrefixLength,
		&i.CacheTrailingDepth,
	)
	return i, err
}

const getStreamRunByID = `-- name: GetStreamRunByID :one
SELECT id, conversation_id, context_id, parent_message_id, provider_id, model_id, status, purpose, started_at, ended_at, error_payload, result_message_id, result_context_id, prefix_hashes, prefix_length, cache_stable_prefix_length, cache_trailing_depth FROM stream_runs WHERE id = $1
`

func (q *Queries) GetStreamRunByID(ctx context.Context, id uuid.UUID) (StreamRun, error) {
	row := q.db.QueryRow(ctx, getStreamRunByID, id)
	var i StreamRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.ContextID,
		&i.ParentMessageID,
		&i.ProviderID,
		&i.ModelID,
		&i.Status,
		&i.Purpose,
		&i.StartedAt,
		&i.EndedAt,
		&i.ErrorPayload,
		&i.ResultMessageID,
		&i.ResultContextID,
		&i.PrefixHashes,
		&i.PrefixLength,
		&i.CacheStablePrefixLength,
		&i.CacheTrailingDepth,
	)
	return i, err
}

const hasRunningStreamForConversation = `-- name: HasRunningStreamForConversation :one
SELECT EXISTS(
    SELECT 1 FROM stream_runs
    WHERE conversation_id = $1 AND status = 'running'
)::BOOLEAN AS has_running
`

// True iff the conversation has any stream_run with status='running'. Used by
// the conversation-lock helper that gates mutating RPCs while a stream is
// in flight (server-side enforcement of the UI's "disabled while streaming"
// behavior).
func (q *Queries) HasRunningStreamForConversation(ctx context.Context, conversationID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasRunningStreamForConversation, conversationID)
	var has_running bool
	err := row.Scan(&has_running)
	return has_running, err
}

const insertStreamChunk = `-- name: InsertStreamChunk :exec
INSERT INTO stream_chunks (stream_run_id, sequence, chunk_type, payload)
VALUES ($1, $2, $3, $4)
`

type InsertStreamChunkParams struct {
	StreamRunID uuid.UUID
	Sequence    int64
	ChunkType   string
	Payload     []byte
}

func (q *Queries) InsertStreamChunk(ctx context.Context, arg InsertStreamChunkParams) error {
	_, err := q.db.Exec(ctx, insertStreamChunk,
		arg.StreamRunID,
		arg.Sequence,
		arg.ChunkType,
		arg.Payload,
	)
	return err
}

const listStreamChunks = `-- name: ListStreamChunks :many
SELECT stream_run_id, sequence, chunk_type, payload, created_at
FROM stream_chunks
WHERE stream_run_id = $1 AND sequence >= $2
ORDER BY sequence
`

type ListStreamChunksParams struct {
	StreamRunID uuid.UUID
	Sequence    int64
}

// Returns persisted chunks for a run, in sequence order, starting at the given
// sequence cursor. Used to replay missed chunks for late subscribers.
func (q *Queries) ListStreamChunks(ctx context.Context, arg ListStreamChunksParams) ([]StreamChunk, error) {
	rows, err := q.db.Query(ctx, listStreamChunks, arg.StreamRunID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreamChunk
	for rows.Next() {
		var i StreamChunk
		if err := rows.Scan(
			&i.StreamRunID,
			&i.Sequence,
			&i.ChunkType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamRunsByConversation = `-- name: ListStreamRunsByConversation :many
SELECT id, conversation_id, context_id, parent_message_id, provider_id, model_id, status, purpose, started_at, ended_at, error_payload, result_message_id, result_context_id, prefix_hashes, prefix_length, cache_stable_prefix_length, cache_trailing_depth FROM stream_runs
WHERE conversation_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListStreamRunsByConversation(ctx context.Context, conversationID uuid.UUID) ([]StreamRun, error) {
	rows, err := q.db.Query(ctx, listStreamRunsByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StreamRun
	for rows.Next() {
		var i StreamRun
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.ContextID,
			&i.ParentMessageID,
			&i.ProviderID,
			&i.ModelID,
			&i.Status,
			&i.Purpose,
			&i.StartedAt,
			&i.EndedAt,
			&i.ErrorPayload,
			&i.ResultMessageID,
			&i.ResultContextID,
			&i.PrefixHashes,
			&i.PrefixLength,
			&i.CacheStablePrefixLength,
			&i.CacheTrailingDepth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunningAsInterrupted = `-- name: MarkRunningAsInterrupted :exec
UPDATE stream_runs
SET status = 'interrupted',
    ended_at = NOW()
WHERE status = 'running'
`

// Called once on server boot. The upstream sockets died with the process and
// cannot be resumed; users see a partial assistant message + retry affordance.
func (q *Queries) MarkRunningAsInterrupted(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markRunningAsInterrupted)
	return err
}

const maxStreamChunkSequence = `-- name: MaxStreamChunkSequence :one
SELECT COALESCE(MAX(sequence), -1)::BIGINT AS max_sequence
FROM stream_chunks
WHERE stream_run_id = $1
`

// Returns the highest persisted sequence for a run, or NULL if none persisted.
func (q *Queries) MaxStreamChunkSequence(ctx context.Context, streamRunID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, maxStreamChunkSequence, streamRunID)
	var max_sequence int64
	err := row.Scan(&max_sequence)
	return max_sequence, err
}

const setStreamRunPrefixHashes = `-- name: SetStreamRunPrefixHashes :exec
UPDATE stream_runs
SET prefix_hashes              = $2,
    prefix_length              = $3,
    cache_stable_prefix_length = $4,
    cache_trailing_depth       = $5
WHERE id = $1
`

type SetStreamRunPrefixHashesParams struct {
	ID                      uuid.UUID
	PrefixHashes            []byte
	PrefixLength            *int32
	CacheStablePrefixLength *int32
	CacheTrailingDepth      *int32
}

// Records the per-message hashes of the rendered wire-prefix for a run plus
// the diagnostics computed against the previous turn (NULL on the first
// turn for a context — no comparison possible).
func (q *Queries) SetStreamRunPrefixHashes(ctx context.Context, arg SetStreamRunPrefixHashesParams) error {
	_, err := q.db.Exec(ctx, setStreamRunPrefixHashes,
		arg.ID,
		arg.PrefixHashes,
		arg.PrefixLength,
		arg.CacheStablePrefixLength,
		arg.CacheTrailingDepth,
	)
	return err
}
