// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_embedder_config.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserEmbedderConfig = `-- name: DeleteUserEmbedderConfig :exec
DELETE FROM user_embedder_config WHERE user_id = $1
`

func (q *Queries) DeleteUserEmbedderConfig(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserEmbedderConfig, userID)
	return err
}

const getUserEmbedderConfig = `-- name: GetUserEmbedderConfig :one
SELECT user_id, type, config, api_key_encrypted, enabled, created_at, updated_at FROM user_embedder_config
WHERE user_id = $1
`

// Returns the user's embedder config row, if any. pgx ErrNoRows on
// missing — callers fall back to the daemon's SPALT_EMBEDDER env var
// (server-default mode).
func (q *Queries) GetUserEmbedderConfig(ctx context.Context, userID uuid.UUID) (UserEmbedderConfig, error) {
	row := q.db.QueryRow(ctx, getUserEmbedderConfig, userID)
	var i UserEmbedderConfig
	err := row.Scan(
		&i.UserID,
		&i.Type,
		&i.Config,
		&i.ApiKeyEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserEmbedderConfigs = `-- name: ListUserEmbedderConfigs :many
SELECT user_id, type, config, api_key_encrypted, enabled, created_at, updated_at FROM user_embedder_config WHERE enabled = TRUE ORDER BY user_id
`

// The worker enumerates this to know which users have configured
// embedders. Returning all rows in one shot is fine — we'd never
// have more than a handful per Spalt instance.
func (q *Queries) ListUserEmbedderConfigs(ctx context.Context) ([]UserEmbedderConfig, error) {
	rows, err := q.db.Query(ctx, listUserEmbedderConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserEmbedderConfig
	for rows.Next() {
		var i UserEmbedderConfig
		if err := rows.Scan(
			&i.UserID,
			&i.Type,
			&i.Config,
			&i.ApiKeyEncrypted,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserEmbedderConfig = `-- name: UpsertUserEmbedderConfig :one
INSERT INTO user_embedder_config (
    user_id, type, config, api_key_encrypted, enabled, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (user_id) DO UPDATE
SET type              = EXCLUDED.type,
    config            = EXCLUDED.config,
    api_key_encrypted = EXCLUDED.api_key_encrypted,
    enabled           = EXCLUDED.enabled,
    updated_at        = NOW()
RETURNING user_id, type, config, api_key_encrypted, enabled, created_at, updated_at
`

type UpsertUserEmbedderConfigParams struct {
	UserID          uuid.UUID
	Type            string
	Config          []byte
	ApiKeyEncrypted []byte
	Enabled         bool
}

// Single-row upsert keyed by user_id. Conflict resolves by replacing
// every field (no merge semantics) — the UI sends the whole row each
// time and "clear my api_key" must work via an empty bytea.
func (q *Queries) UpsertUserEmbedderConfig(ctx context.Context, arg UpsertUserEmbedderConfigParams) (UserEmbedderConfig, error) {
	row := q.db.QueryRow(ctx, upsertUserEmbedderConfig,
		arg.UserID,
		arg.Type,
		arg.Config,
		arg.ApiKeyEncrypted,
		arg.Enabled,
	)
	var i UserEmbedderConfig
	err := row.Scan(
		&i.UserID,
		&i.Type,
		&i.Config,
		&i.ApiKeyEncrypted,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
