// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_tts_config.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserTTSConfig = `-- name: DeleteUserTTSConfig :exec
DELETE FROM user_tts_config WHERE user_id = $1
`

func (q *Queries) DeleteUserTTSConfig(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserTTSConfig, userID)
	return err
}

const getUserTTSConfig = `-- name: GetUserTTSConfig :one
SELECT user_id, kind, config, api_key_encrypted, provider_ref, enabled, created_at, updated_at FROM user_tts_config
WHERE user_id = $1
`

// pgx ErrNoRows on missing — callers treat absence as the apple_local
// default (on-device synthesis, nothing to configure).
func (q *Queries) GetUserTTSConfig(ctx context.Context, userID uuid.UUID) (UserTtsConfig, error) {
	row := q.db.QueryRow(ctx, getUserTTSConfig, userID)
	var i UserTtsConfig
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.Config,
		&i.ApiKeyEncrypted,
		&i.ProviderRef,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserTTSConfig = `-- name: UpsertUserTTSConfig :one
INSERT INTO user_tts_config (
    user_id, kind, config, api_key_encrypted, provider_ref, enabled, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
ON CONFLICT (user_id) DO UPDATE
SET kind              = EXCLUDED.kind,
    config            = EXCLUDED.config,
    api_key_encrypted = EXCLUDED.api_key_encrypted,
    provider_ref      = EXCLUDED.provider_ref,
    enabled           = EXCLUDED.enabled,
    updated_at        = NOW()
RETURNING user_id, kind, config, api_key_encrypted, provider_ref, enabled, created_at, updated_at
`

type UpsertUserTTSConfigParams struct {
	UserID          uuid.UUID
	Kind            string
	Config          []byte
	ApiKeyEncrypted []byte
	ProviderRef     *uuid.UUID
	Enabled         bool
}

// Single-row upsert keyed by user_id; conflict replaces every field
// (the service sparse-merges before calling, and "clear my api_key"
// must work via an empty bytea).
func (q *Queries) UpsertUserTTSConfig(ctx context.Context, arg UpsertUserTTSConfigParams) (UserTtsConfig, error) {
	row := q.db.QueryRow(ctx, upsertUserTTSConfig,
		arg.UserID,
		arg.Kind,
		arg.Config,
		arg.ApiKeyEncrypted,
		arg.ProviderRef,
		arg.Enabled,
	)
	var i UserTtsConfig
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.Config,
		&i.ApiKeyEncrypted,
		&i.ProviderRef,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
